### ISSUE TITLE
Проблемы с англ. распознаванием 

### ISSUE THREAD

**Issue by Grentari** [OneMoreGres/ScreenTranslator#102]
На win 10 и версии ST 3.2.1 такого не замечал. После перехода на актуальную win 11 и 3.2.3 (все обновления применил) увидел подобную проблему.
Причем если выбрать яз. распознавания Cebuano то будет успешно распознавать англ.
![image](https://user-images.githubusercontent.com/59330648/172069219-bb00b2f1-ba5e-42ce-8ddc-01675815ab3a.png)
![image](https://user-images.githubusercontent.com/59330648/172069245-22925a5f-5a03-4e91-9032-d55d1b2d2e22.png)

**Comment by OneMoreGres** [comment]
Да, часто мусор появляется. Посмотрю

**Comment by OneMoreGres** [comment]
Доработал распознавание. Сейчас распознает нормально
