### ISSUE TITLE
Проблема с переводом

### ISSUE THREAD

**Issue by Artlemoon** [OneMoreGres/ScreenTranslator#105]
Был у меня перерыв от использования программы +/- месяц не пользовался. Сейчас появилась нужда и вот столкнулся с такой проблемой - переводит текст через раз
![p](https://user-images.githubusercontent.com/95495491/174620874-d148234c-7b1e-4b13-958b-9d9d04bc41fc.png)
![p2](https://user-images.githubusercontent.com/95495491/174620902-ec645bb8-b6e6-46e5-b47b-59e27f27a752.png)
win 11 
Последняя версия программы 3.2.3
Грешу на мною добавленную коррекцию
![1](https://user-images.githubusercontent.com/95495491/174621448-571deb75-acb2-4e55-a6e8-f38052dfdc85.png)

**Comment by OneMoreGres** [comment]
Здравствуйте. Нет, проблема не в коррекции. Я обновил библиотеку распознавания и что-то пошло не так :)
Уже описана такая проблема в #102 , так что эту закрываю. Все никак времени не найду сесть посмотреть как следует.

**Comment by Artlemoon** [comment]
> Здравствуйте. Нет, проблема не в коррекции. Я обновил библиотеку распознавания и что-то пошло не так :) Уже описана такая проблема в #102 , так что эту закрываю. Все никак времени не найду сесть посмотреть как следует.

Найдите пожалуйста время. Очень полезная программа(

**Comment by DmitriyMX** [comment]
@Artlemoon если что, на версии 3.2.1 распознавание всё ещё корректно работает

**Comment by OneMoreGres** [comment]
Да я уже почти. Там просто другие проблемы вылезли. Постараюсь на этой неделе выложить

**Comment by Artlemoon** [comment]
Большое спасибо!
