### ISSUE TITLE
How can I customize a select region on screen ?

### ISSUE THREAD

**Issue by fayendrare** [OneMoreGres/ScreenTranslator#106]
Hello,

First of all, thank you for this software, it helps me a lot.

In the point 3 of the usage part you say that we can customize a select region on screen.
How can I do it? And if we can not can you add a feature that can translate an area whitout selecting it? Or select all screen by default.
And I don't understand the setting "capture the saved area" is maybe what I am looking for.

Thank you in advance.

**Comment by OneMoreGres** [comment]
Hi! Select an area via the right button or right click while selecting to customize. You can change languages and save the area there.

**Comment by fayendrare** [comment]
Ok I see, thank you very much you help me a lot.
Большое спасибо 
Have a nice day.
