### ISSUE TITLE
Ошибка загрузки страницы для перевода

### ISSUE THREAD

**Issue by Klausinus** [OneMoreGres/ScreenTranslator#11]
Сначала все было нормально потом при обновлении скачались еще переводчики, и программа стала ругаться. Пробывал переустановить, все равно вылазит эта ошибка "Ошибка загрузки страницы для перевода"

**Comment by OneMoreGres** [comment]
На всех переводчиках так? В режиме отладки что-то грузится? С интернетом проблем нет/не через прокси?

**Comment by Klausinus** [comment]
Да было через прокси, поставил нет, все стало нормально, спс
