### ISSUE TITLE
Version 3.3.0 - 3.2.2 no downloads settings, translate etc win 11 x64

### ISSUE THREAD

**Issue by valek97** [OneMoreGres/ScreenTranslator#116]
Привет. Скачивал версию 3,3,0-3,2,2 x64 нет возможности скачать в нем переводчики, распознавание языка. Пашет только 3,2,1.

**Comment by OneMoreGres** [comment]
Привет. Ошибка какая-то выдается? Нужно установить все `vcredist` из папки с программой. Кому-то помогает использование 32-битной версии (`vcredist` и `openssl`). Еще можно попробовать установить/удалить `Chrome`. Он прописывает сертификаты `github`, как доверенные.

**Comment by valek97** [comment]
Нет, ошибок нет. Просто пустой экран, как у некоторых был.  Либы ставил сразу. Нормально пашел 3,2,1 и старше. А новые не пашут уже пол года, что ставил систему, что не ставил, пофиг(даже после сноса системы). Использую вин 11 х64

**Comment by OneMoreGres** [comment]
Пустой экран во вкладке обновлений или в "окне переводчика"? Если первое, то попробуйте включить в настройках запись лога в файл, проверить обновления, отключить запись лога и посмотреть/скинуть сюда лог. Если второе, то возможно перевод вообще отключен или переводчики неактивны/без интерфейса. Тогда активируйте все во вкладке перевода

**Comment by valek97** [comment]
Не удается воспроизвести, хоть и почистил все, что мог. В указанных версиях при загрузке окна - обновление - пустая страница была, ни одного поля. Сейчас все подтягивает нормально. Можно закрывать.
