### ISSUE TITLE
Закрывается после открытия. Linux

### ISSUE THREAD

**Issue by Nord1cWarr1or** [OneMoreGres/ScreenTranslator#117]
**Describe the bug**
Закрывается сразу после запуска

**Logs**
Невозможно получить

**Desktop:**
 - OS: Garuda Linux x86_64
 - Desktop environment (linux only): KDE Plasma 5.25.5
 - App version (release archive name): 3.3.0 AppImage

**Additional context**
После первого запуска, скачал русский язык, скачал нужные переводчики. Нажал ОК. Приложение закрылось. С тех пор при запуске выдаёт уведомление, что запущено, но тут же закрывается (иконка исчезает из трея)

**Comment by OneMoreGres** [comment]
Попробуйте запустить с `QTWEBENGINE_DISABLE_SANDBOX=1` (в терминале в папке с программой `QTWEBENGINE_DISABLE_SANDBOX=1 ./ScreenTranslator.appimage`).
Если дело в настройках, то удалите/переместите файл `~/.config/Gres/ScreenTranslator.conf`, чтобы сбросить настройки, и запустите программу. Еще можно удалить ресурсы из `~/.local/share/Gres/ScreenTranslator`

**Comment by Nord1cWarr1or** [comment]
Удаление ресурсов и настроек не помогло, после повторной конфигурации всё то же самое.

При запуске через консоль (до этого запускал через гуи):
```
DevTools listening on ws://127.0.0.1:58803/devtools/browser/e814926c-8a84-4473-b887-565f39646bf0
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:58803
fish: Job 1, './ScreenTranslator-3.3.0.AppIma…' terminated by signal SIGSEGV (Address boundary error)
```
А это при запуске  с параметром`./ScreenTranslator.appimage QTWEBENGINE_DISABLE_SANDBOX=1`:
```
DevTools listening on ws://127.0.0.1:59411/devtools/browser/5c88f51d-b4f4-49f2-b0f9-9196064f97dd
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:59411
[3:3:0100/000000.690861:ERROR:zygote_linux.cc(614)] Zygote could not fork: process_type renderer numfds 3 child_pid -1
[3:3:0100/000000.690956:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
fish: Job 1, './ScreenTranslator-3.3.0.AppIma…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by Nord1cWarr1or** [comment]
А, действительно, так работает. Благодарю
