### ISSUE TITLE
Japanese text contain spaces, causing occasional weird translation

### ISSUE THREAD

**Issue by DaLimCodes** [OneMoreGres/ScreenTranslator#119]
Hi, for some reason when capturing Japanese text it seems to introduce spaces because I'm getting a strange translation
![unknown](https://user-images.githubusercontent.com/3626687/193377249-1f3b6769-fc26-4133-a147-029e91223d1d.png)

At first I thought it was just google being silly, but when I copied the captured text and pasted it to notepad, I noticed there's a lot of spaces added in between each captured characters, and because of this, Google did some strange translation as you can see here
![unknown](https://user-images.githubusercontent.com/3626687/193377152-93311ae8-5b58-4001-98fe-9a9df282a7aa.png)
And when the spaces are removed, it seems to be translating it fine now
![unknown (1)](https://user-images.githubusercontent.com/3626687/193377156-6b0004d8-32a0-45a3-8274-948d3aec5df8.png)

Please note that I took these screenshots above yesterday (around 12 hours ago?) and for some reason it looks like google translate isn't giving me that translation again. That being said, I think my point still stands because introducing spaces in Japanese text seems to cause slightly different translation (which is fine if it's just minor difference, but hard to tell if it suddenly changes meaning drastically). 

I don't believe Japanese uses space character in 99% case so I'm wondering if there's an option to auto drop the spaces?

PS: DeepL fares better at least, but as you can see, it's also slightly different translation due to the spaces (this one I took about 15 minutes ago)
![brave_QwYmIRyFeV](https://user-images.githubusercontent.com/3626687/193377144-f1a8b5f3-59f9-496f-88e4-9b9d2f94dfd7.png)

**Comment by DaLimCodes** [comment]
By the way, love the app a lot!

**Comment by OneMoreGres** [comment]
Hi! There is the user substitution option in the settings. Here you can set ' ' to '' (space to nothing) substitution for Japanese language. It's applied just before the translation

**Comment by DaLimCodes** [comment]
Ahh, I didn't expect the setting "Correction" can actually do that, thank you so much for pointing me to the right direction!

I can confirm this is all good now!
[image](https://user-images.githubusercontent.com/3626687/193403044-871d018b-8880-43d4-8b54-d77f3bdc6eb4.png)
