### ISSUE TITLE
Would you add translator(papago) IF this is possible?

### ISSUE THREAD

**Issue by rlaqjatl3362** [OneMoreGres/ScreenTranslator#12]
this is korea website's(www.naver.com) translator. 
https://papago.naver.com/

is this possible to add PAPAGO in translator?

**Comment by OneMoreGres** [comment]
Seems like it's possible. I'll take a closer look later.

**Comment by OneMoreGres** [comment]
I've just added it. Update scripts from the app of manually to try it. However this script might be buggy because of more generic issues (repetition of old translations).

**Comment by rlaqjatl3362** [comment]
> I've just added it. Update scripts from the app of manually to try it. However this script might be buggy because of more generic issues (repetition of old translations).

thank you :)
