### ISSUE TITLE
Время перевода стало странным

### ISSUE THREAD

**Issue by MagistrEnot** [OneMoreGres/ScreenTranslator#123]
Я выбрал текст для перевода, и тут все сломалось
После выбора текста, проходит 15-20 секунд и показывает перевод, раньше требовалось 1-2-3 секунды.
Я также решил покликать везде, и эффекта небыло за исключением момента когда кликать.
Если выбрать текст, и в эти 15-20 секунд выбрать текст любой еще раз, то переведет как и раньше за 1-2-3 секунды, так можно переводить пока 15-20 секунд не пройдут, тойсть пока не покажет перевод который я запросил в самом начале.
Иногда такое было на определенном тексте, тойсть во всем тексте такое случалось только с(например 2 строчкой), все остальное ScreenTranslator переводил как и всегда. Но сейчас это со все текстом большим или маленьким кусочком текста.

Конечно я мог просто чтото пропустить в настройках, но я проверил несколько раз и если не ошибаюсь все так как и было в день установки.

windows 11
3.3.0/win64

**Comment by OneMoreGres** [comment]
Скорее всего какой-то скрипт перевод тормозит. Попробуйте повыключать разные в настройках. Можно отобразить окно переводчика через иконку трея и посмотреть, грузятся ли страницы

**Comment by MagistrEnot** [comment]
> Скорее всего какой-то скрипт перевод тормозит. Попробуйте повыключать разные в настройках. Можно отобразить окно переводчика через иконку трея и посмотреть, грузятся ли страницы

Я выбрал отображение в трей окне, все точно также. А вот смена переводчика помогла, из все работает только Bing.js и Deepl.js, остальные google.js/google_api.js, baidu.js, papago.js, yandex.js, либо работают 15-20 секунд(как я написал в первом комментарие, либо вообще не показывают перевод(либо просто дольше переводят)

**Comment by MagistrEnot** [comment]
Спасибо за помощь

**Comment by OneMoreGres** [comment]
Немного подправил скрипт Google. Надеюсь будет лучше :)
Насколько помню, Яндекс и papago требуют открытое окно переводчика. Еще яндекс очень быстро начинает показывать капчу
