### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by HelpMeWithThisTranslatorPlease** [OneMoreGres/ScreenTranslator#126]
Я переводил переводил, все было хорошо, и тут в один день все сломалось. Перевод както странно стал работать, во-первых как когда-то случалось, перевод у гугла сломался и переводит только через секунд 10-15, как и в прошлый раз если в эти 10-15 секунд еще раз сделать перевод то все переведет как и всегда, и опять же как и в прошлый раз можно переводить сколько угодно пока не покажет первый запрошенный перевод через эти 10-15 секунд, тогда я менял способ перевода на bing, но теперь и с ним чтото не так, он то переводит, то даже слово не переводит. И еще кое-что, перед тем как это произошло, ScreenTranslator стал говорить о том что есть обновления, но я проверил все, саму версию переводчика, версию переводчика в переводчике. не работает. Я также пробовал полностью удалить все связанное с ScreenTranslator и переустановить, также не помогло. Еще за день(или два или три) я баловался с антивирусами. все 

 - OS: [windows 11]
 - App version [3.3.0-win64]

**Comment by OneMoreGres** [comment]
Попробуйте открыть окно переводчика (через иконку в трее). Похоже Google начал "требовать", чтобы оно было открыто.
Насчет обновлений. В какой-то строке должно быть написано, что есть обновление. Иначе предупреждение не выдавалось бы. Ресурс из этой строки и надо обновить. Или вы имеете в виду, что обновились и все равно не работает?

**Comment by HelpMeWithThisTranslatorPlease** [comment]
![Без имени](https://user-images.githubusercontent.com/117914605/201212644-3cd7febb-3205-432f-9316-ffd743b98fc8.png)
Вот это каждый запуск ScreenTranslator появляеться. Я нажимал на все что в красном круге, там все "Послденяя версия"
![ё](https://user-images.githubusercontent.com/117914605/201213259-940f9f00-d714-4951-b60d-00ff4a41d674.png)

**Comment by OneMoreGres** [comment]
Это сообщение значит, что давно не проверяли обновления. Оно должно исчезать после проверки. Похоже мой косяк. Попробуйте поставить ненулевой интервал проверки обновлений и нажать "проверить сейчас". Должно исчезнуть.

Но это напрямую к переводу не относится. У меня гугл работает, если открыто окно переводчика. Вы так пробовали?

**Comment by HelpMeWithThisTranslatorPlease** [comment]
Да, я нажимал на "Проверить сейчас(с нулевым и ненулевым интервалом), это не работает.

Нет я так не делал.Я не уверен правильно ли я сделал, у меня изначально работают два google переводчика, google.js и google_api.js, я выключил google.js и сразу же все стало хорошо
(Я подумал что эти два google.js и google_api.js нужны друг для друга)

И еще помог способ включить сразу все переводчики и поставить "Переходить к следующему переводчику после (секунды(я поставил две)) и он стал переводить как и раньше, и в моменты когда стали появляться эти задержки в 10-15 секунд, они перестали переводить 10-15 секунд и время уменьшилось до 4-8 секунд

**Comment by HelpMeWithThisTranslatorPlease** [comment]
Стоп, простите меня, кажется я сильно сглупил, я решил еще подумать что могло быть не так и вспомнил, я же сказал что у меня было включено два переводчика google.js и google_api.js, один из них не работает, и когда у меня стояло два переводчика у меня было включено ''Переходить к следующему переводчику после (секунды)'' и у меня тогда было 15 секунд как и в проблеме перевода, получается когда я переводил и ждал перевод, переводчик который не работал переводил 10-15 секунд и только потом показывался перевод от работающего переводчика(google_api.js), и также перевод работал в эти 10-15 секунд потому-что переводил не google.js(который не работает и уже занят попыткой перевести), а переводил работающий google_api.js.

Простите... я только сейчас решил задуматься...

**Comment by HelpMeWithThisTranslatorPlease** [comment]
Ну а bing и правда стал дольше некоторый текст переводить, причем условия в которых написан этот текст одинаковые, даже не вижу что может заставлять его долго переводить, ведь это даже с одним словом случается

**Comment by HelpMeWithThisTranslatorPlease** [comment]
Еще раз простите (///_///)

**Comment by OneMoreGres** [comment]
По поводу "Переходить к следующему переводчику .." да, оно так и работает. Пробует первый переводчик, если он не успевает, то переходит в следующему, и т.д. Каждый переводчик самостоятельный, так что да, `google` и `google_api` друг другу не нужны и между ними как раз и была эта пауза.
Все-таки попробуйте в трее выбрать "Показать переводчик" и проверить обычный google. У меня так заработал.
Насчет bing не знаю. Если бы вообще не работал... Опять же если выбрать "Показать переводчик", то можно посмотреть, как грузится его страница.
А по поводу "сглупил" не берите в голову. Тикеты для того и нужны, чтобы разобраться

**Comment by HelpMeWithThisTranslatorPlease** [comment]
Спасибо
