### ISSUE TITLE
the settings not open but the app is work 

### ISSUE THREAD

**Issue by Mohamed-ELnaZer** [OneMoreGres/ScreenTranslator#127]
when i cleck on settings to open its show on taskbar but not abeer on screen

**Comment by Mohamed-ELnaZer** [comment]
![image](https://user-images.githubusercontent.com/59163874/202020415-bd16fac6-f3be-4d91-af43-be43a280b4d5.png)

**Comment by OneMoreGres** [comment]
Does the taskbar icon has a preview? Maybe it's somewhere on another screen (which is inactive now). It can happen if you use portable mode and run the app on different machines. The app remembers the last position of the window and restores it.
Try moving the window via the taskbar context menu or rename the `settings.ini` file in the app's folder to something else and restart the app.
