### ISSUE TITLE
Захват и Повторить захват ничем не отличаются

### ISSUE THREAD

**Issue by mike2003** [OneMoreGres/ScreenTranslator#132]
По идее "Повторить захват" должен использовать предыдущие настройки выделения и сразу показать перевод для нового текста. Так в аналогичных программах. Но в обоих режимах нужно снова выделять рамкой и нет никакой разницы между этими командами.
Так в чем же повтор? Баг?

**Comment by OneMoreGres** [comment]
"Захват" делает новый снимок экрана, а "повторить захват" выделяет на старом. В этом и различие. То, что вы описали, это скорее "захват сохраненных зон"

**Comment by mike2003** [comment]
"выделяет на старом"
А что значит "на старом"?

**Comment by OneMoreGres** [comment]
На старом снимке экрана, т.е. с последнего скриншота. Для статичной картинки это не заметно, но если экран изменяется, то смысл есть
