### ISSUE TITLE
deepl.js  is out

### ISSUE THREAD

**Issue by super4444** [OneMoreGres/ScreenTranslator#135]
hello

deepl.js don't  Works

thank you

**Comment by OneMoreGres** [comment]
Works for me. It just wants the translator's window to be visible

**Comment by super4444** [comment]
some time ago deepl was translating without needing this window open, it's a bit of a shame, but useful now to know, thanks for the tip

**Comment by OneMoreGres** [comment]
Yeah. Many translators worked without opening the window, and Yandex didn't ask to solve the captcha after 2 translations... But they live own lives and I'm trying to react to their changes with a minimal effort
