### ISSUE TITLE
Переводчик Deepl

### ISSUE THREAD

**Issue by UniqueTiger** [OneMoreGres/ScreenTranslator#140]
Deepl начал творить кашу, первое предложение нормально переводит, потом переводит второе нормально, но после нового перевода еще раз пишет перевод старого предложения, что делать?

Вот что в самом окне перевода, может поможет вам понять.

> userscript:deepl.js: 20 start translate Fortunately, we completed our cleaning duties on time. en ru
userscript:deepl.js: 62 setting url https://www.deepl.com/translator#en/ru/Fortunately%2C%20we%20completed%20our%20cleaning%20duties%20on%20time.
https://static.deepl.com/js/translator_late.min.$d02fc5.js: 2 DeepL Translator 
https://static.deepl.com/js/translator_late.min.$d02fc5.js: 2 Welcome to DeepL.com!
https://www.deepl.com/translator#en/ru/Fortunately0C%20we%20completed%20our%20cleaning%20duties%20on%20time.: 0 Autofocus processing was blocked because a document already has a focused element.
https://static.deepl.com/js/sentry.min.$314a47.js: 2 Module already defined 'FeatureManager'
https://static.deepl.com/js/sentry.min.$314a47.js: 2 Module already defined 'LMT_UI_SystemNotification'
https://static.deepl.com/js/sentry.min.$314a47.js: 2 [FeatureManager.defineType] /translator/core/selectLangUI is already defined!
userscript:deepl.js: 13 translated text К счастью, мы выполнили свои обязанности по уборке вовремя. old  size 59 0
userscript:deepl.js: 20 start translate Your performance was acceptable. Therefore, you will not be punished for
your misdemeanor this morning. Be grateful! en ru
userscript:deepl.js: 13 translated text Ваше выступление было приемлемым. Поэтому вы не будете наказаны за
ваш проступок сегодня утром. Будьте благодарны! old К счастью, мы выполнили свои обязанности по уборке вовремя. size 114 59
userscript:deepl.js: 20 start translate Wasn't the act of cleaning simply...exhilarating? en ru
userscript:deepl.js: 13 translated text Разве акт уборки не был просто... захватывающим?
ваш проступок сегодня утром. Будьте благодарны! old Ваше выступление было приемлемым. Поэтому вы не будете наказаны за
ваш проступок сегодня утром. Будьте благодарны! size 96 114
userscript:deepl.js: 20 start translate A sense of peace and tranquility washes over me at the sight of a squeaky
clean toilet. en ru
userscript:deepl.js: 13 translated text Чувство мира и спокойствия охватывает меня при виде скрипящего
чистого туалета.
ваш проступок сегодня утром. Будьте благодарны! old Разве акт уборки не был просто... захватывающим?
ваш проступок сегодня утром. Будьте благодарны! size 127 96

**Comment by SerjIgnat** [comment]
Нет решения? Такая же хрень происходит

**Comment by SerjIgnat** [comment]
I have the same problem. The script seems to select and delete only the first line instead of all the text, and inserts the following text in its place

**Comment by OneMoreGres** [comment]
Не было времени как следует посмотреть. Исправил. Теперь все строки склеиваются перед переводом. Можете обновить и проверить.

Fixed it. Now joining lines before translation. You can update and test it.

**Comment by UniqueTiger** [comment]
Спасибо большое за исправление, теперь все хорошо работает.
