### ISSUE TITLE
Ошибка при обновлении ресурсов

### ISSUE THREAD

**Issue by Oleg-Artist** [OneMoreGres/ScreenTranslator#143]
Здравствуйте. На одном компьютере у меня приложение установилось замечательно. А на втором при первом запуске возникла ошибка и не удаётся установить файлы распознавания, перевода, коррекции. На скрине видно текст ошибки из уведомления Windows. Отключение файрволла не дало результатов
![2023-02-18_17-56-44](https://user-images.githubusercontent.com/97278739/219867204-7ad92043-9a24-4da1-ac90-a37fa8f0af37.png)

**Comment by OneMoreGres** [comment]
Здравствуйте. Есть похожие issues (#96 , #98). Попробуйте обновить/установить `vsredist...exe` из папки с программой. Еще попробуйте установить Google Chrome (после установки можно удалить).
Закрываю, т.к. дубликат
