### ISSUE TITLE
Not showing translated text

### ISSUE THREAD

**Issue by dtndmd** [OneMoreGres/ScreenTranslator#146]
**Describe the bug**
Not showing translated text

**To Reproduce**
1. Press capture hotkey.
2. Only the recognized text is displayed, not the translated text.

**Expected behavior**
Get translation of recognized text.

**Logs**
[screen-translator-2023-02-25-13-01-22.log](https://github.com/OneMoreGres/ScreenTranslator/files/10830200/screen-translator-2023-02-25-13-01-22.log)

**Screenshots**
![SCREENTRANSLAD](https://user-images.githubusercontent.com/46117970/221335179-5bcf23c6-e0dc-4624-bf5f-1d932541f708.PNG)

**Desktop (please complete the following information):**
Windows 10
ScreenTranslator-3.3.0-win64

**Comment by OneMoreGres** [comment]
According to the log file DeepL just failed to translate the text. Try enabling another translator in the settings. Also check for updates if you haven't in a while
