### ISSUE TITLE
Add options for copying original text or translated text.

### ISSUE THREAD

**Issue by Kuju29** [OneMoreGres/ScreenTranslator#150]
Is it possible for you to add options for copying original text or translated text? 

![image](https://user-images.githubusercontent.com/22098092/232989704-f14f55b3-811c-4c50-9d77-64be5d4bba5c.png)
I want "Copy result to clipboard" to have options or add shortcuts.
- Copy only the original text.
- Copy only the translated text.
- Copy both the original text and the translated text.

If you can do it I would be very grateful. I tried PowerToys "Text Extractor". It's slow and some words are not as good as yours.

**Comment by OneMoreGres** [comment]
There is a similar issue (#112). I'm closing this one as duplicate.
I don't know when I'll continue working on this app, so I can't give dates.
