### ISSUE TITLE
Ошибка сегментирования (образ памяти сброшен на диск)

### ISSUE THREAD

**Issue by dimjkee90** [OneMoreGres/ScreenTranslator#158]
При запуске ошибка сегментирования

![image](https://github.com/OneMoreGres/ScreenTranslator/assets/36246157/1f37890a-e47b-42c2-9136-1a52d0d06634)

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.10
DISTRIB_CODENAME=kinetic
DISTRIB_DESCRIPTION="Ubuntu 22.10"

5.19.0-46-generic

**Comment by OneMoreGres** [comment]
`QTWEBENGINE_DISABLE_SANDBOX=1` пробовали? ](https://github.com/OneMoreGres/ScreenTranslator/issues/148#issuecomment-1500954292), https://github.com/OneMoreGres/ScreenTranslator/blob/master/README.md#faq)

**Comment by dimjkee90** [comment]
Да с этой переменной все заработало, большое спасибо!
