### ISSUE TITLE
Selecting Area and other ideas.

### ISSUE THREAD

**Issue by AstraeaZero** [OneMoreGres/ScreenTranslator#16]
Hello, your application is great, I am trying to beat Yakuza 0 with this app, can you add automatic translation options from the selected window in real time? Add an additional tab in the options with editing colors of selected background, font color and choosing the font and size of text, for example, background in black and white text written with arial black 18 (like on Youtube), and the option to remove the preview of the original language, select area and everything will be translated automatically? Such a possibility would be great, there are so many great Visual Novel games in English. I know I could learn English but it is not so easy when you did not have it in school, half of what I know, I learned from games but I am still weak in this language. Thanks for your time, work and have a good day or night 👍 PS:
I think there are many people who have been looking for a tool like this. Because I have met people who were looking for a translator on the fly. You can make something bigger with this app 💃 
![translate](https://user-images.githubusercontent.com/44085780/70178929-62d60c80-16dd-11ea-939a-a619f48465a8.png)

**Comment by OneMoreGres** [comment]
Hi! I've added it to TODO list. But it's moving really slooow... :(

**Comment by AstraeaZero** [comment]
Anyway, I still holding my fingers for this project :D you do a great job and no one can tell you that you work too slowly, because it's your project: D Everyone also has their own private life.

**Comment by OneMoreGres** [comment]
Added most things in v3.0.0
