### ISSUE TITLE
Снова сломался перевод на DeepL

### ISSUE THREAD

**Issue by RedCapcha** [OneMoreGres/ScreenTranslator#160]
Не начинает автоматический перевод и не выбирает язык с которого нужно перевески и на какой нужно перевести при том, что всё настроено. Начинает переводить лишь после того как вручную выставишь языки и сам впишешь в переводчик пару слов. В логах переводчика пишет следующее:
userscript:deepl.js: 24 start translate Hoothoot en ru
userscript:deepl.js: 69 setting url https://www.deepl.com/translator#en/ru/Hoothoot
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 DeepL Translator 
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Welcome to DeepL.com!
https://www.deepl.com/translator#en/ru/Hoothoot: 0 Autofocus processing was blocked because a document's URL has a fragment '#en/ru/Hoothoot'.
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null
https://static.deepl.com/js/translator_early.min.$f8e66e.js: 1 Module already defined 'LMT_UI_SystemNotification'
https://static.deepl.com/js/translator_early.min.$f8e66e.js: 1 Module already defined 'FeatureManager'
https://static.deepl.com/js/utils.chunk.$731c71.js: 1 [FeatureManager.defineType] /translator/core/selectLangUI is already defined!
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/core/selectedLanguages,/translator/core/textareas 
Missing:  
Required by: "/translator/common/speakSourceText"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/core/selectedLanguages,/translator/core/textareas,/translator/core/requestHandling 
Missing:  
Required by: "/translator/common/speakTargetText"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/core/languageManagement,/translator/core/translationBackend,/translator/core/config,/translator/core/textareas,/translator/common/observeTextSession,/translator/core/requestHandling,/translator/common/alternativeTranslations,/translator/environment/analyticsSession 
Missing: /translator/common/observeTextSession 
Required by: "/translator/common/sendTranslationState"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/core/languageManagement,/translator/core/retranslationServices,/translator/webTranslatorCore,/translator/formality/persist,/translator/core/config,/translator/core/predefinedState 
Missing:  
Required by: "/translator/formality/core"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/core/translateSourceSentences,/translator/core/config,/translator/formality/core 
Missing: /translator/formality/core 
Required by: "/translator/formality/ad"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/environment/localizedTexts,/translator/core/targetLanguages,/translator/formality/ad,/translator/common/openPage 
Missing: /translator/formality/ad 
Required by: "/translator/formality/adUi"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/core/config,/translator/formality/core,/translator/common/openPage 
Missing: /translator/formality/core 
Required by: "/translator/formality"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/core/domElements,/translator/core/translateSourceSentences,/translator/core/textareas,/translator/core/predefinedState,/translator/core/requestHandling,/translator/common/observeTranslationBackend 
Missing:  
Required by: "/translator/common/observeTextSession"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/core/config,/translator/core/languageManagement,/translator/core/textareas,/translator/common/observeTextSession,/translator/environment/sendAnalytics 
Missing: /translator/common/observeTextSession 
Required by: "/translator/common/analytics"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/common/analytics,/translator/environment/sendAnalytics 
Missing: /translator/common/analytics 
Required by: "/translator/web/analytics"
https://static.deepl.com/js/sentry.min.$1fffce.js: 1 [FeatureManager] Required features could not be resolved within 5000ms 
Required: /translator/webTranslatorCore,/translator/core/config,/translator/core/textareas,/translator/core/requestHandling,/translator/common/share,/translator/common/shareUrl 
Missing: /translator/common/share 
Required by: "/translator/common/shareTargetText"
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'removeChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'appendChild' of null
userscript:deepl.js: 17 translated text П old  size 1 0
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'removeChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'appendChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'removeChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'appendChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'removeChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'appendChild' of null
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'removeChild' of null
userscript:deepl.js: 24 start translate Pidgey en ru
userscript:deepl.js: 69 setting url https://www.deepl.com/translator#en/ru/Pidgey
https://static.deepl.com/js/translator_late.min.$475cf2.js: 44 Uncaught TypeError: Cannot read property 'appendChild' of null
userscript:deepl.js: 24 start translate spawns: en ru
userscript:deepl.js: 17 translated text порождает: old П size 10 1

**Comment by OneMoreGres** [comment]
Никак руки не дойдут...

**Comment by RedCapcha** [comment]
> Никак руки не дойдут...

Надо хотя бы доползти

**Comment by RedCapcha** [comment]
> Никак руки не дойдут...

Можно сказать что переводчик теперь в нерабочем состоянии, так как DeepL был единственным внятным вариантом.
