### ISSUE TITLE
translated into german

### ISSUE THREAD

**Issue by tafeilgh** [OneMoreGres/ScreenTranslator#161]
**Describe the bug**
Translation not shown or translated into german

**To Reproduce**
1. Click on exe
2. Capture text
3. See error

**Expected behavior**
Hope English translated into Chinese

**Logs**
[screen-translator-2023-08-09-17-34-42.txt](https://github.com/OneMoreGres/ScreenTranslator/files/12300712/screen-translator-2023-08-09-17-34-42.txt)

**Screenshots**
![屏幕截图(141)](https://github.com/OneMoreGres/ScreenTranslator/assets/100503528/3c323e66-69a5-4639-aa85-472985d09d9a)

**Desktop (please complete the following information):**
 - OS:  windows 10
 - App version (release archive name): [e.g. 3.0.0-win32, 3.0.0-compatible-win64]
3.3.0
**Additional context**
Set translate to Chinese, when capture, I can see eng>chi_sim, but translate to German.

Click show translater, change German to Chinese in deepl translation, then it can translate to Chinese.

The next time I start the program, I still get the same error.

**Comment by OneMoreGres** [comment]
Deeps is currently broken (#160). I'm slowly fixing it :). Other translators should work.
Closing as duplicate
