### ISSUE TITLE
The settings window does not appear.

### ISSUE THREAD

**Issue by Djindustrie** [OneMoreGres/ScreenTranslator#169]
The settings window does not appear. I'm told it's an outdated version and needs to be included.

I would like to ask for help.

**Comment by OneMoreGres** [comment]
You're opening it via tray menu and it doesn't appear? Try Alt-Tab. Maybe it's outside of the screen

**Comment by Djindustrie** [comment]
That was my first thought too but unfortunately none of the options I could think of worked.
I get the error message when I start it.
Current version might be outdated.
Check for updates to silence this
warmng.

**Comment by OneMoreGres** [comment]
This is not an error. It just says that binary is quite old and there might be updates available. It will stop warn after you click "check for updates" in the settings window. 
But if you can't open the settings window at all then you can't use a program anyway (you have to install recognition languages and translation scripts). You can try cleaning registry `.../Software/Gres/ScreenTranslator` or smth similar.

**Comment by Djindustrie** [comment]
Many thanks for the help.
It helped me alot.
