### ISSUE TITLE
Translate better easily

### ISSUE THREAD

**Issue by ImVing** [OneMoreGres/ScreenTranslator#171]
**Is your feature request related to a problem? Please describe.**
The program that recognizes text from images automatically adds a carriage return at the end of each line, causing complete sentences to be interrupted. Having to remove line breaks and manually add spaces for the website to fully translate the meaning of the sentence, this is very annoying.

**Describe the solution you'd like**
I think you should add a function to automatically remove line breaks and replace them with spaces. It will always create a meaningful sentence for sentences with commas or periods.

**Describe alternatives you've considered**
You should have more options for the program to recognize words better manually.
For example: Turn on the option to automatically replace line breaks with spaces to always create meaningful sentences.
For example: Automatically change uppercase to lowercase for Manhwa and Manga.

**Comment by OneMoreGres** [comment]
There are several similar issues (#128, #69).

In short: you can add manual correction from end-of-line character ('\n') to, say, space (' ') in the settings.

Closing as duplicate
