### ISSUE TITLE
Correction configuration does not save

### ISSUE THREAD

**Issue by GLC022** [OneMoreGres/ScreenTranslator#172]
Language does not fix the desired language.

1. Go to 'Settings'
2. Click on 'Correction'
3. Select the desired Language.
4. Click Apply.
5. Notice the Language has returned to its original setting.

The Language should remain the one I selected, in this case, Portuguese.

**Desktop:**
    - OS: Windows 10 Pro, version 22H2, 64-bit operating system, x64-based processor

**Comment by OneMoreGres** [comment]
Hi! 
It's the user correction settings. It describes which recognized text should be replaced with which corrected text when translated into a specific language. In this case, only lines containing the current recognition language are used. The program does not save lines without recognized text filled, as this would not make sense.
Returning to your issue - just ignore this table if you don't want to replace any specific text. If you want - fill all columns.

**Comment by GLC022** [comment]
I understood. Thanks.
