### ISSUE TITLE
It is not possible to select the language

### ISSUE THREAD

**Issue by marcelo2100** [OneMoreGres/ScreenTranslator#177]
I can't translate anything. every time I select my language in "correction" and save the settings, it always goes back to the "Afrinkaans" language. My system is Windows 10 with 64bits

**Comment by OneMoreGres** [comment]
The `Correction` tab is for the recognized text correction, it doesn't affect translation. Change it if you regularly experience recognition errors. If you want to change the translation language, go to the `translation` tab. Install translators in `update` tab if not yet.
For more details see #172
