### ISSUE TITLE
Contextual Translation Issue with Screen Captured Text

### ISSUE THREAD

**Issue by Eng-Ahmed-Rifai** [OneMoreGres/ScreenTranslator#178]
**Describe the bug**
When using the ScreenTranslator to translate text captured from the screen, the translation is done line-by-line, which leads to a loss of context and potentially incorrect translations.

**Screenshots**
![image](https://github.com/OneMoreGres/ScreenTranslator/assets/110114267/470d57d4-f47e-48f6-8c00-07a0509430e1)

**Suggested enhancement:**
Modify the text processing prior to translation to concatenate lines into a single text block or handle newline characters in a way that does not break the context.

**Additional context:**
This issue significantly affects the usability of the application for languages where context is crucial to the meaning of the text. A fix would greatly enhance the quality of translations produced by the application.

**Desktop (please complete the following information):**
 - OS: Win 11
 - App version 3.3.0

**Comment by OneMoreGres** [comment]
There are several similar issues (#128 , #69).

In short: you can add manual correction from end-of-line character ('\n') to, say, space (' ') in the settings.

Closing as duplicate
