### ISSUE TITLE
Incorrect screen capture on linux system

### ISSUE THREAD

**Issue by Landgraf132** [OneMoreGres/ScreenTranslator#18]
In Manager.cpp you can replace 
```
QPixmap pixmap = screen->grabWindow (0, geometry.x (), geometry.y (),
                                         geometry.width (), geometry.height ());
```

to
```
QPixmap pixmap = screen->grabWindow (0, 0, 0,
                                         geometry.width (), geometry.height ());
```

**Comment by OneMoreGres** [comment]
What issues are you facing otherwise? What desktop environment are you using? I've just tested it on cinnamon and KDE - works fine.

**Comment by Landgraf132** [comment]
kubuntu 19.10 with 2 monitors. Without this fix, after I press ctrl+alt+z a see it:
![Screenshot_20200102_155013](https://user-images.githubusercontent.com/16545917/71667820-bdfc2d00-2d77-11ea-9f22-cd84000f39af.png)

**Comment by OneMoreGres** [comment]
With what Qt version you've recompiled the program? Is this the behaviour of the recompiled program or the original appimage? I've just tested the appimage on Kubuntu 18.04 with 2 displays with different aspect ratios, and there was no missing parts. So maybe it's a related to newer versions of Qt or KDE.
Grabbing from {0,0} will not work for virtual desktops, consisting from more then one screen. Maybe "available**Virtual**Geometry" must be used instead of "availableGeometry".
Can't check more right now.

**Comment by Landgraf132** [comment]
I'm recompile this with qt 5.12.4. Original behaviour with AppImage is correct. When i recompilled program, availableGeometry and availableVirtualGeometry show me equal result. 

I do an experiment and realized that the error was probably not here
![Screenshot_20200105_145701](https://user-images.githubusercontent.com/16545917/71779878-ee3c0980-2fcb-11ea-8f0a-5dc0e24b032b.png)
This is display location work  ok with screenTranslator.

![Screenshot_20200105_145720](https://user-images.githubusercontent.com/16545917/71779885-0e6bc880-2fcc-11ea-8936-65268a2adcfe.png)
This is display location (my default) conduct to image distortion as I show in start post.

**Comment by Landgraf132** [comment]
I found a solution to a similar problem.
https://github.com/olav-st/screencloud/blob/432533cc506eae4afa128e0c3018492cdeee3dbc/src/screenshooter.cpp

Is such a solution suitable for ScreenTranslator for new Qt version?

**Comment by OneMoreGres** [comment]
Thanks for the tip. Can't check it right now, but it looks like this should work.
Btw how did you build it with newer Qt? Where did you get QWebKit from?

**Comment by Landgraf132** [comment]
I got QWebKit from the standard repository kubuntu 19.10
libqt5webkit5/eoan,now 5.212.0~alpha3-3 
libqt5webkit5-dev/eoan,now 5.212.0~alpha3-3
