### ISSUE TITLE
It not working.. pls help

### ISSUE THREAD

**Issue by blue4ever01** [OneMoreGres/ScreenTranslator#187]
Hi everyone, 

Why the app always give back original language? did i wrongly set config? For example i need translate from english to italian, but it always show english only :(. Pls help me

![1](https://github.com/OneMoreGres/ScreenTranslator/assets/174021464/d23dace3-4dec-499b-a812-bb23025d71bd)
![image](https://github.com/OneMoreGres/ScreenTranslator/assets/174021464/34e29a00-90c4-4081-8d88-824c55daea99)
![image](https://github.com/OneMoreGres/ScreenTranslator/assets/174021464/d7e7b2ec-5700-47d8-aa8e-89c7801ebaae)
![image](https://github.com/OneMoreGres/ScreenTranslator/assets/174021464/b545eb03-5a2e-427a-859c-92d5144e1701)

**Comment by doktorjasper** [comment]
![image](https://github.com/OneMoreGres/ScreenTranslator/assets/121597413/d64501ec-ce47-4ff5-87a4-a5dd6ef4dba4)
 in translation section select targetlanguage and in recognition section select english default language and use google api

**Comment by blue4ever01** [comment]
ty problem solved. Instead of choosing english in translation, i picked english middle instead haha

**Comment by doktorjasper** [comment]
good job A useful application that helps us improve ourselves
