### ISSUE TITLE
i get this erorr whin i ran app on ubuntu 24 

### ISSUE THREAD

**Issue by reza18s** [OneMoreGres/ScreenTranslator#188]
**log**
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

DevTools listening on ws://127.0.0.1:41785/devtools/browser/604b3e63-f8a0-4118-b62b-e1eccf29f66a
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:41785
Segmentation fault (core dumped)

**Desktop (please complete the following information):**
 - OS: [ ubuntu 24]
 - Desktop environment (linux only): [e.g. KDE, Gnome]
 - App version (release archive name): [3.3.0]

**Comment by OneMoreGres** [comment]
Most likely `QTWEBENGINE_DISABLE_SANDBOX=1` workaround would help (https://github.com/OneMoreGres/ScreenTranslator?tab=readme-ov-file#faq). But wayland it not supported anyway. You'll likely have a black screen when try to capture
