### ISSUE TITLE
Warning when starting a program on Linux systems

### ISSUE THREAD

**Issue by Landgraf132** [OneMoreGres/ScreenTranslator#19]
In GlobalActionHelper.cpp, registerHotKey and unregisterHotKey, return error value incorrect. May be simply return true?

**Comment by Landgraf132** [comment]
I can create pull request, if you give me access.

**Comment by OneMoreGres** [comment]
Are you sure that you don't have the same shortcuts already registered? I've tried it on cinnamon and KDE - it warns only when the shortcuts are already in use.
Btw, you don't need any permissions to *create* pull request. Though I'm not sure that there is an issue.

**Comment by Landgraf132** [comment]
I checked it, yes, it seems the problem is not quite in that.

Regarding the creation of the branch\pull. I get next error:
```
remote: Permission to OneMoreGres/ScreenTranslator.git denied to Landgraf132.
fatal: unable to access 'https://github.com/OneMoreGres/ScreenTranslator.git/': The requested URL returned error: 403
```

**Comment by OneMoreGres** [comment]
Usually you won't get write permissions to a repository and pull requests must be created [from a fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by Landgraf132** [comment]
Thank you for the explanation!
