### ISSUE TITLE
Вылетает на Linux

### ISSUE THREAD

**Issue by tomright** [OneMoreGres/ScreenTranslator#190]
**Describe the bug**

**To Reproduce**
1) Открыл программу
2) Поставил на обновление все языки
3) Закрыл программу
4) При следующем открытии выходит уведомление: Экранный переводчик запущен
5) Ничего не происходит и нет иконки приложения в трее

**Screenshots**
![Снимок экрана_2024-08-18_14-36-08](https://github.com/user-attachments/assets/85fa925a-e0d1-4b98-a748-26060433cdf4)

**Desktop (please complete the following information):**
OS: linux mint 21
DE:  4,16
 - App version (release archive name):  ScreenTranslator-3.3.0.AppImage

**Comment by OneMoreGres** [comment]
Похоже на [это](https://github.com/OneMoreGres/ScreenTranslator?tab=readme-ov-file#faq). 
`QTWEBENGINE_DISABLE_SANDBOX=1 ./ScreenTranslator-3.3.0.AppImage`. 
Можно добавить в ярлык или скрипт. Общесистемной эту переменную лучше не делать

**Comment by tomright** [comment]
Спасибо, действительно проблема была в этом. Спасибо за помощь!
