### ISSUE TITLE
RCC: Error in 'Recources.qrc': Cannot find file 'translations/translation_en.qm'

### ISSUE THREAD

**Issue by Voskrese** [OneMoreGres/ScreenTranslator#2]
в описании нет

**первая ошибка, вроде разобрался**

root@net:/opt/ScreenTranslator# qmake
RCC: Error in 'Recources.qrc': Cannot find file 'translations/translation_en.qm'
RCC: Error in 'Recources.qrc': Cannot find file 'translations/translation_ru.qm'
root@net:/opt/ScreenTranslator#
root@net:/opt/ScreenTranslator/translations# ls
translation_en.ts  translation_ru.ts
root@net:/opt/ScreenTranslator/translations# cp translation_en.ts translation_en.qm
root@net:/opt/ScreenTranslator/translations# cp translation_ru.ts translation_ru.qm

**вторая ошибка**

Recognizer.cpp:3:31: fatal error: tesseract/baseapi.h: Нет такого файла или каталога
 #include <tesseract/baseapi.h>
                               ^
compilation terminated.
Makefile:598: ошибка выполнения рецепта для цели «Recognizer.o»
make: *** [Recognizer.o] Ошибка 1

**разобрался, заглянул в папку скрипты**

sudo apt-get install libxcb-util0-dev fakeroot libtesseract-dev libleptonica-dev qt5-qmake libqt5webkit5-dev libqt5x11extras5-dev qttools5-dev-tools g++

не хватало 
НОВЫЕ пакеты, которые будут установлены:
  libleptonica-dev libtesseract-dev libtesseract3

**третья ошибка** 
root@net:/opt/ScreenTranslator# ./ScreenTranslator
Error opening data file /usr/share/tesseract-ocr/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.Failed loading language 'eng'
Tesseract couldn't load any languages!

**доустановил** 
apt install tesseract-ocr-eng
Настраивается пакет tesseract-ocr-eng (3.04.00-1)

скомпилилось все под вынь 10 wsl bash

автор, не бросай разработку) полезная утилита) спасибо

**Comment by OneMoreGres** [comment]
На всякий случай поясню.

1. Надо выполнить `lrelease ScreenTranslator.pro` (lrelease - в папке с qmake), тогда переводы скомпилируются куда нужно.
2. Да, надо поставить (или собрать самому) `libtesseract-dev`  с зависимостями. Остальные библиотеки - это для чистой системы от для других ошибок :)
3. Можно так, можно скачать [вручную](https://github.com/tesseract-ocr/tessdata) и задать в переменной окружения TESSDATA_PREFIX путь к папке, в которой лежит папка tessdata, в которой лежат скачанные языки :) , либо собрать libtesserract самому и там указать какой угодно путь.

Насчет разработки.. Программа, в основном, делает, что от нее ожидают. Так что я ее пока не трогаю. Благо есть, чем заняться. Но предложения потихоньку собираю :)
