### ISSUE TITLE
Translation didn’t seems to work.

### ISSUE THREAD

**Issue by 314pies** [OneMoreGres/ScreenTranslator#21]
The translation feature didn’t seems working anymore.

**Comment by OneMoreGres** [comment]
Try to update the translation scripts.
To do it from the settings window, the app must be "run as administrator" (for now). Or you can manualy download files from [here](https://github.com/OneMoreGres/ScreenTranslator/tree/master/translators) and put them into translators folder near ScreenTranslator.exe (replacing the exising ones).

**Comment by 314pies** [comment]
It works, thanks!

**Comment by OneMoreGres** [comment]
The translation scripts live their own lifes.
Each release of the program comes with the latest scripts, but after that the scripts may update separately until the next release of the program.

**Comment by 314pies** [comment]
Yeah, I understand that.
I mean at least made a new release build or let users know they may need to update the translation script in [_README.md_](https://github.com/OneMoreGres/ScreenTranslator/blob/master/README.md), the last build is already 2 years ago and the translation feature aren't working by default. 

This software is really awesome and It will be unfortunate if someone else miss it because they think it's out-of-date and didn't work anymore (which I almost did).

**Comment by OneMoreGres** [comment]
I'll update the readme. Also, I'm currently working on the next release and I'll add some checks related to this issue. 

P.S. omg, 2 years...
