### ISSUE TITLE
Windows installer for 3.0 version

### ISSUE THREAD

**Issue by asv285041** [OneMoreGres/ScreenTranslator#24]
Hey,
First big thank you for such nice tool.
I used for a while version 2. and happy to see new release 3.0.
As i see there are only files for 32 and 64 version for Windows. 
Could you please make installer for them? i've tried to use just files and start translator, but there is no recognition data and no translation data in folders.

Will be great to have automatically installed all required data.

Thank you

**Comment by 314pies** [comment]
The translator and recognizer can be installed via the setting menu.
Just go to Settings -> Update, and click "Check now". The list of recognizer and translator should appear, right click on the target translator and recognizer and select install/update, then click "Apply updates" and you should have them installed.
![image](https://user-images.githubusercontent.com/20402192/80468025-40d17500-8971-11ea-81a9-806ce4b74384.png)

**Comment by OneMoreGres** [comment]
You can also update multiple items at once.
As for an installer, I don't plan to do it. You can do anything you need in the program
