### ISSUE TITLE
Nothing's working.

### ISSUE THREAD

**Issue by Haurabe** [OneMoreGres/ScreenTranslator#25]
Every time I highlight an area of text for translation, the application itself starts to translate and if I move the cursor over it in the tray, it simply closes. The settings seem to have been set correctly, and when selected it shows "eng to ru".
Used both deepl and yandex. Everything was updated to the latest version.
I'm attaching the log.
[stLOG.txt](https://github.com/OneMoreGres/ScreenTranslator/files/4549336/stLOG.txt)

**Comment by OneMoreGres** [comment]
Try using this library version. Tell if it helps, pls.
[tess.zip](https://github.com/OneMoreGres/ScreenTranslator/files/4553738/tess.zip)

**Comment by Haurabe** [comment]
> Try using this library version. Tell if it helps, pls.
> [tess.zip](https://github.com/OneMoreGres/ScreenTranslator/files/4553738/tess.zip)

The application does not close anymore, but it produces an error:
"It failed to translate the text (Timeout)"

**Comment by OneMoreGres** [comment]
Open the translation window (via tray menu) and look if pages are being loader there. If not - check internet access (firewall/proxy). If yes, but slow - increase 'timeout' value in settings. If yes and fast - send logs for this translation script (via 'write trace to file' setting or just copy text from the translation window's tab).
Plus, try this version. It should be a little faster [tess1.zip](https://github.com/OneMoreGres/ScreenTranslator/files/4554060/tess1.zip) (I'm deciding which one should be used by default)

**Comment by Haurabe** [comment]
> Open the translation window (via tray menu) and look if pages are being loader there. If not - check internet access (firewall/proxy). If yes, but slow - increase 'timeout' value in settings. If yes and fast - send logs for this translation script (via 'write trace to file' setting or just copy text from the translation window's tab).
> Plus, try this version. It should be a little faster [tess1.zip](https://github.com/OneMoreGres/ScreenTranslator/files/4554060/tess1.zip) (I'm deciding which one should be used by default)

With the new version of tess1.zip deepL is working. But the bug with the letter "I" is still there.

**Comment by OneMoreGres** [comment]
This library doesn't affect translation. Only recognition and only performance.
I don't know how to fix "|" other then by using auto substitution.
DeepL works. Maybe not always. But it's just like any other translator.
Also, AFAIK, Yandex requires translator window to be visible during translation

**Comment by Haurabe** [comment]
Okay, I think I got the letter "I" sorted out.
>This library doesn't affect translation. Only recognition and only performance.
As soon as I changed it, the translation went straight to work. And the last version works probably better than the one you sent me the first time.
If there are any more bugs, I'll write them down here, and if not, I'll probably close this topic for nothing.
Thank you.
