### ISSUE TITLE
Error prevents apllication from opening

### ISSUE THREAD

**Issue by CommicKick69ing** [OneMoreGres/ScreenTranslator#28]
**Describe the bug**
An eroor pops ups saying that numerous .dll files are missing even though the git hub page doesnt tell me how to download any of this.

**To Reproduce**
1. Click on 'the exe
2. See error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - App version: 3.0.0
 - App bitness version (windows only): [Win64]

**Comment by OneMoreGres** [comment]
Since you didn't mention any library name, I guess you should install `vc-redist*.exe` from the app archive

**Comment by OneMoreGres** [comment]
Guess it works now. Closing the issue. Comment if you still have this issue
