### ISSUE TITLE
Capture saved area feature wont work

### ISSUE THREAD

**Issue by CommicKick69ing** [OneMoreGres/ScreenTranslator#29]
**Describe the bug**
I capture an area and if I try to select "Capture saved area" it is greyed out and non selectable

**To Reproduce**
1. Capture an area of the screen
2. Try click on Capture saved area but it is greyed out and non selectable
3. nothing happends

**Expected behavior**
You can select Capture saved area

**Screenshots**
<img width="151" alt="Capture" src="https://user-images.githubusercontent.com/40266764/80892031-f49a7380-8c95-11ea-8e58-703ddf0ea540.PNG">

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - App version: 3.0 [e.g. ersion (windows only): [win32]

**Comment by OneMoreGres** [comment]
You have to check `save area` option in capture area settings window (opens via right mouse button when selecting)

**Comment by CommicKick69ing** [comment]
I did

**Comment by OneMoreGres** [comment]
Click out of the settings widget or on selected rect to apply changes

**Comment by OneMoreGres** [comment]
Guess it works now. Closing the issue. Comment if you still have this issue
