### ISSUE TITLE
The screen translator wont work properly

### ISSUE THREAD

**Issue by bannerquitalig** [OneMoreGres/ScreenTranslator#30]
![444444](https://user-images.githubusercontent.com/65006726/81375982-306d8700-9135-11ea-8129-1c5125c9e6f4.PNG)

I cant capture images

![image](https://user-images.githubusercontent.com/65006726/81376032-48dda180-9135-11ea-8c16-870dd3be05cf.png)

I cant translate anything

it is always saying failed to init OCR engine

**Comment by OneMoreGres** [comment]
1. There are issues templates. Please use them
2. Please use search before opening new issue (#27)
