### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by Harchvertelol** [OneMoreGres/ScreenTranslator#33]
**Describe the bug**
Crash program if in path to program folder we have russain (all not english?) characters.

**To Reproduce**
1. Go to Setting
2. Click on update (Russian and English recognition, Google.js translator)
3. Click "Apply"
4. Crash with log: [0712/010815.239:ERROR:icu_util.cc(170)] Invalid file descriptor to ICU data received.

After this program crasing on start.

How I fixed this problem: place folder of program into path WITHOUT russian characters.

**Comment by OneMoreGres** [comment]
Hi. Try adding an empty `qt.conf ` file into the program's folder. I don't know why, but it worked for me.
