### ISSUE TITLE
It does not work at all.

### ISSUE THREAD

**Issue by toprak** [OneMoreGres/ScreenTranslator#35]
Firstly, hi i am the guy who opened the linux ocr issue, hope it is nice to see me again :D Anyways, my problem is whenever I capture anywhere after then capture program says it has stopped working.
**To Reproduce**
Click capture and select are and app will be gone.

[screen-translator-2020-08-14-22-30-14.zip](https://github.com/OneMoreGres/ScreenTranslator/files/5076813/screen-translator-2020-08-14-22-30-14.zip)
**Logs**
Application log file recorded during an error.
To start recording a log file, open the settings window,
enable the 'write trace file' option and apply the settings.

**Desktop (please complete the following information):**
Windows 7, latest version, updates are done.

**Additional context**
BTW, did you add multiple meaning feature?

**Comment by OneMoreGres** [comment]
Hi. Set `compatible` library version in recognition settings.
On the multiple meanings of words: no, I haven't added it (it's in the wishlist, but I don't think I'll do it anytime soon).

**Comment by OneMoreGres** [comment]
Guess it works. Comment if I'm wrong
