### ISSUE TITLE
Vertical text

### ISSUE THREAD

**Issue by AdeenDragon** [OneMoreGres/ScreenTranslator#36]
Is there a way to set ScreenTranslator to expect vertical text, commonly used in Japanese for example?

**Comment by OneMoreGres** [comment]
There is no any specific handling for vertical text. As a workaround, you can try using **_vert** languages or capture each vertical text separately.

**Comment by AdeenDragon** [comment]
Oh, I see it now!  I’ve not seen vertical text handled as a different
language before, but it does make sense to handle it that way.

**Comment by OneMoreGres** [comment]
Added some tweaks in v3.2.0. Should work better now
