### ISSUE TITLE
Translate result is the same language that I just circled

### ISSUE THREAD

**Issue by buttercheese2020** [OneMoreGres/ScreenTranslator#37]
**Describe the bug**
Translate result is the same language that I just circled
**To Reproduce**
1. select the thing that I wanted to translate 
2. wait for it
3. and it shows the same language same line

**Expected behavior**
show the translation language that I select

issue:
![bug](https://user-images.githubusercontent.com/75562217/101276838-c44a2300-37ea-11eb-846a-eb6db232d2e5.png)

ScreenTranslator settings:
![Settings 2020_12_6 下午 05_46_56](https://user-images.githubusercontent.com/75562217/101276905-41759800-37eb-11eb-8aa6-4e52271526da.png)
![Settings 2020_12_6 下午 05_47_00](https://user-images.githubusercontent.com/75562217/101276908-43d7f200-37eb-11eb-8101-2367bcd8364a.png)
![Settings 2020_12_6 下午 05_47_07](https://user-images.githubusercontent.com/75562217/101276907-43d7f200-37eb-11eb-9cab-75db517bc59c.png)
![Settings 2020_12_6 下午 05_47_11](https://user-images.githubusercontent.com/75562217/101276906-433f5b80-37eb-11eb-91d4-08640ffe97a6.png)

**Desktop (please complete the following information):**
-OS: Windows 10
-App version: ScreenTranslator-3.1.0-win64

**Comment by OneMoreGres** [comment]
Hi! I've just updated translation script, so it should work now. Download the new version from the app.

**Comment by buttercheese2020** [comment]
thanks that did work
