### ISSUE TITLE
Error in recurring translations

### ISSUE THREAD

**Issue by jhoanjdv** [OneMoreGres/ScreenTranslator#38]
Hi, the program always shows an error on the second translation attempt. (timed out)

1. Right click and save translated area
2. Try to capture the saved area again
3. See error timed out (and the previously translated text is displayed again, only original text) 

**Expected behavior**
The new translation with the previously selected area

**Logs**
I do not know where the log file is saved, sorry.

**Screenshots**
![1](https://user-images.githubusercontent.com/68834869/103445043-2cefb880-4c4e-11eb-902e-39a9e7485b76.jpg)
![2](https://user-images.githubusercontent.com/68834869/103445047-37aa4d80-4c4e-11eb-9632-35fb3dd67e4c.jpg)
![3](https://user-images.githubusercontent.com/68834869/103445049-3b3dd480-4c4e-11eb-9051-47a6360b85b1.jpg)
![4](https://user-images.githubusercontent.com/68834869/103445053-3ed15b80-4c4e-11eb-8990-1313d972cce6.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
  - App version 3.1.0

**Comment by OneMoreGres** [comment]
Hi. I couldn't reproduce the error both on windows and linux.

The main issue here is that translator recognizes the same text for the new translation. Enable image showing for results window in settings and check if the input image is correct (contains the new text). Timeout error is likely just a consecuense of translating the same text.

Log file can be saved via settings window (`general` -> `write trace file`). Maybe it will give some hints

**Comment by jhoanjdv** [comment]
Hi, this time I was able to locate the log file. And when I enabled the imageshowing for results it always gave me the error time out.

[screen-translator-2021-01-04-22-12-27.txt](https://github.com/OneMoreGres/ScreenTranslator/files/5767530/screen-translator-2021-01-04-22-12-27.txt)

I hope you can help me.

**Comment by OneMoreGres** [comment]
Does the result window contains an image with new text when timeout error occurs? Looks like it processes the same image several times

**Comment by jhoanjdv** [comment]
Yes, I can see the same image when trying to make a new capture.
The program does not translate the current screen but translates the image saved in memory again. Did the log file show anything useful?

**Comment by OneMoreGres** [comment]
Also update translations scripts. It is not related to image capture, but at least you should not get timeout errors.

**Comment by jhoanjdv** [comment]
1. Was there already a new image (text) on the screen when you started capturing? (exactly when you started it, not when the results window appeared)?
   - When I press the keys to make a new capture, the last image I translated is shown. But if I press Esc and then try to capture again the error goes away. That is, it is always displayed once after the last capture. Then it works notmal.

2. Do you capture it via hotkeys or via tray menu?
   - Via hotkeys (Alt+Z)

3. Do you close the results window before the new capture?
   - How can I do that? The results disappear when I click on the game.

4. Do you have any custom/slow window animations or you just use default windows theme?
   - Default windows theme

5. Also update translations scripts. It is not related to image capture, but at least you should not get timeout errors.
   - Already did. Thanks

**Comment by OneMoreGres** [comment]
Correct me where I'm wrong:

1. start normal capture (hotkey or tray's `Capture`)
2. select area with `TEXT_1` -> right click -> activate `Save`
3. click on area or press `enter`
4. results window appears with `TEXT_1`
5. click somewhere and hide results window
6. wait util `TEXT_2` appears on screen (in game)
7. press hotkey (for `Capture saved areas`)
8. get timeout error (before scripts update)
9. results window appears with `TEXT_1`
10. click somewhere and hide results window
11. `TEXT_2` is still on screen (in game)
12. press hotkey (for `Capture saved areas`)
13. results window appears with `TEXT_2`
14. repeat from step 5 with `TEXT_3` and so on (i.e. the actual in-game text is shown in the results window only on the second try)

**Comment by jhoanjdv** [comment]
Yes, in exactly that order the error appears. Always in the same way every two attempts

**Comment by OneMoreGres** [comment]
Does it happen in any program (browser?) or in games only (or in one specific game)? And does normal capture (not saved areas) sometimes shows previous image?

**Comment by jhoanjdv** [comment]
I have done several tests with the browser and other games and the program works perfect. Even in the same game runs perfect windowed. The problem seems to appear when playing in fullscreen :(

**Comment by jhoanjdv** [comment]
It seems that when it is in full screen the program saves the image of the last translation in memory and is not updated for the next capture

**Comment by OneMoreGres** [comment]
Actually fullscreen apps [should not work at all and not supported](https://github.com/OneMoreGres/ScreenTranslator#limitations).
Usually games provide the `frameless window` mode that looks just like fullscreen. You can use it, if available.

**Comment by Trongatk** [comment]
Has this issue been resolved yet?

**Comment by OneMoreGres** [comment]
Fullscreen apps are still not supported
