### ISSUE TITLE
Невозможно обновить языки\добавить\изменить переводчики.

### ISSUE THREAD

**Issue by Haurabe** [OneMoreGres/ScreenTranslator#39]
Здравствуйте!
Приложение постоянно предлагает мне обновится, хотя во вкладке "обновлений" абсолютно пусто. Тоже самое и со вкладкой "переводчики". Версия(3.1.1\x64). 
В настройках ничего не менял\запускал от администратора\ - что я сделал не так?

**Comment by Haurabe** [comment]
Неожиданно после перекачивания программы и установки vc_redist всё вроде как заработало.

**Comment by OneMoreGres** [comment]
Здравствуйте!
Возможно приложение предлагало **проверить** обновления. Если так, то сообщение исчезнет после их проверки.
Плюс, начиная с версии 3.0.0, запуск от имени администратора больше не нужен.
