### ISSUE TITLE
Ability to choose language in hotkeys

### ISSUE THREAD

**Issue by asv285041** [OneMoreGres/ScreenTranslator#4]
First of all, thank you for such nice utility.

Could you please make addtional feature to have hot keys for different languages.
Actually im using utility as screen grabber and copy text without translation.
Sometimes it is russian, sometimes   - english.
And now i need to go to settings and change recognition language everytime.

is it possible?

Thank you

**Comment by OneMoreGres** [comment]
You can choose recognition language in capture mode's popup menu (right-click when selecting recognition area). You can also remove/disable unused languages if the menu is too big.
Have you tried it?
If it doesn't suit your needs I can add your feature to TODO list. But it doesn't have timeline..

**Comment by asv285041** [comment]
Perfect, right click is more then enough. Thank you
