### ISSUE TITLE
Правки распознанного текста/Яндекс API

### ISSUE THREAD

**Issue by Grentari** [OneMoreGres/ScreenTranslator#40]
Перестали работать правки текста. Правлю, распознаю, а текст сбрасывается до изначально распознанного. Все обновления последней версии.
Возможно ли подключить Яндекс API, как это реализовано в XUnity.AutoTranslator. Или возможно есть другой способ обхода автоматических запросов Яндекса?

**Comment by OneMoreGres** [comment]
Если правильно понял, в чем проблема (issue не по шаблону) - то поправил. Но оно и раньше не должно было работать. К концу недели выложу (может еще какие-то изменения накопятся).
По поводу API - не думаю, что это многим нужно. Но если очень хочется, то можно самому написать скрипт на основе google_api.js. Навскидку, нужно будет поменять url и функцию разбора ответа (а может и текущая подойдет)
