### ISSUE TITLE
How to add recognizer? I select a language in the update tab and hit apply, the message says "no action selected".

### ISSUE THREAD

**Issue by robertxchen66** [OneMoreGres/ScreenTranslator#41]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Application log file recorded during an error.
To start recording a log file, open the settings window,
enable the 'write trace file' option and apply the settings.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10, ubuntu 18.04]
 - Desktop environment (linux only): [e.g. KDE, Gnome]
 - App version (release archive name): [e.g. 3.0.0-win32, 3.0.0-compatible-win64]

**Additional context**

**Comment by OneMoreGres** [comment]
RIght-click on language and select 'install' before applying changes
