### ISSUE TITLE
无法更新，打开错误提示。

### ISSUE THREAD

**Issue by snmin** [OneMoreGres/ScreenTranslator#42]
![image](https://user-images.githubusercontent.com/44972156/107150228-bfbdfa00-6954-11eb-9447-6951db9f1682.png)
![image](https://user-images.githubusercontent.com/44972156/107150241-ce0c1600-6954-11eb-94f7-d59121435b7e.png)
![image](https://user-images.githubusercontent.com/44972156/107150247-d2383380-6954-11eb-9a32-02eda8d16804.png)

**Comment by OneMoreGres** [comment]
https://github.com/OneMoreGres/ScreenTranslator/blob/master/README.md 
https://github.com/OneMoreGres/ScreenTranslator/wiki/FAQ

Most likely you should start from https://github.com/OneMoreGres/ScreenTranslator/wiki/FAQ#update-checkdownload-error
