### ISSUE TITLE
jpn_vert Language Package Catastrophic Errors

### ISSUE THREAD

**Issue by Thecat8413** [OneMoreGres/ScreenTranslator#44]
**Describe the bug**
When Using the jpn_vert language setting, the output of the OCR is gibberish. This is then correctly passed the the translator, which understandably returns more gibberish.  

**To Reproduce**
Using Packages Japanese and jpn_vert. (Assuming this is the correct package per comments on Issue #36)

1. Open this Test Image in Browser: [https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/0defd578-acc6-4efd-a77f-42187cfab2e8/02-japanese-02.jpg](url)

2. With the Japanese Package selected, run translation on both Horizontal and Vertical Sections. 
     a. Horizontal Section 
![image](https://user-images.githubusercontent.com/47541088/111860415-4206ea00-8915-11eb-8be1-674e9eff2ac0.png)
     b. Vertical Section
![image](https://user-images.githubusercontent.com/47541088/111860424-51863300-8915-11eb-96ad-2aba2fc9d53d.png)
This returns correctly, although the input from the OCR to the Translator on the vertical section is grammatically broken. 

3. Repeat Step 2 with the jpn_vert Package
     a. Horizontal Section 
![image](https://user-images.githubusercontent.com/47541088/111860369-13890f00-8915-11eb-99b7-8b3991a47436.png)
     b. Vertical Section 
![image](https://user-images.githubusercontent.com/47541088/111860386-256ab200-8915-11eb-83dc-954ae69eef85.png)
Output from OCR is Garbled

4. See error?

**Expected behavior**
Should return the same translation, for the correct version of text. 

**Logs**
**_Note: During the log file recording I first ran the jpn_vert package, then the Japanese package._** 
[screen-translator-2021-03-20-00-41-16.txt](https://github.com/OneMoreGres/ScreenTranslator/files/6174974/screen-translator-2021-03-20-00-41-16.txt)
Added a .txt to allow GitHub upload. 

**Screenshots**
Added In-Line

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App version (release archive name): 3.1.2-win64

**Additional context**
N/A

**Comment by OneMoreGres** [comment]
Hi! The original issue #36 is still open, so there are no proper handling for the vertical text yet.

**Comment by Thecat8413** [comment]
> Hi! The original issue #36 is still open, so there are no proper handling for the vertical text yet.

Ahh. Based on the comments on #36 I assumed that the _vert version had been implemented. Do you have any idea when the vertical text version will be implemented?

**Comment by OneMoreGres** [comment]
Try [one of these](https://github.com/OneMoreGres/ScreenTranslator/actions/runs/673933275)

**Comment by OneMoreGres** [comment]
Applied this change in v3.2.0
