### ISSUE TITLE
Suggestion: Set a Default Recognizer and Translator

### ISSUE THREAD

**Issue by dsnvwlmnt** [OneMoreGres/ScreenTranslator#45]
I nearly gave up on this program after fighting it for 30min+ trying to get it to translate anything. And yes, that's with the instructions hidden in the About box.

My suggestion would be to provide more defaults so that the program does something out of the gate. This way the user has a better idea of what to do to make the program work. Include the recognizer for Chinese (or something, Cherokee if you desperately want to keep the initial install small). Translators are tiny, choose one as a default and include it! (Note: it's completely unclear why you would need more than 1 translator, what the differences between them are, and why or when you would want to use multiple.)

I can imagine some pushback on including a 2-9MB default language. An alternative would be simply changing the font color to red for areas of the Settings UI that are missing. I.e. things that need to be set for the program to function in the first place. So the default install would look like: Update in red, and under Update, "recognizers" would be in red (since there are none to start), and "translators" would be in red (if you don't include any). Until those are set, the program doesn't work but it's not always clear exactly why.

**Comment by OneMoreGres** [comment]
The app, recognizers and translators are updated independently, so it could lead to unusable setup if I pack them together. Not to mention, having the Cherokee recognizer doesn't make the app more usable for most people than not having it at all.
There are some tray messages that warn if you don't have the recognizers/translators installed or set by default.
I'll think about highlighing settings' sections that require some actions.
As for translators: You may want to use different translators if they don't work or you don't like the result. Using multilple translators means that the app will use multiple translators to translate your text :) The first succeeded will give you the translation.

**Comment by OneMoreGres** [comment]
Added highlighting of pages with errors. Also added error messages on these pages. All in v.3.2.0
