### ISSUE TITLE
Suggestion: Make the Workflow More Visible

### ISSUE THREAD

**Issue by dsnvwlmnt** [OneMoreGres/ScreenTranslator#46]
I suggest moving the "program workflow" out of the About and somewhere more obvious.

My first thought would be just keep it always visible on the Settings pane. You have tons of UI space below the 7 categories on the left.

**Comment by OneMoreGres** [comment]
It's a one-time message, so I don't think it should be always visible.
Maybe renaming About to Help will do better..

**Comment by OneMoreGres** [comment]
Renamed About to Help in v3.2.0
