### ISSUE TITLE
Suggestion: Clarify How to Update and/or Improve the UI

### ISSUE THREAD

**Issue by dsnvwlmnt** [OneMoreGres/ScreenTranslator#47]
The biggest UI issue I came across is that it's not clear how to Update anything in the first place. It took me a while to figure out that the only way to do that is by **right-clicking** on any given line. There's an Apply Updates button, but that misleads you, as it doesn't do anything until after you've right-clicked, "Install/Update".

How about putting checkboxes beside each downloadable thing (with a checkmark for things that are already downloaded), the way the Translation tab has checkboxes for which translators you want to use? If not, at least mention somewhere how to update things (i.e., right-click).

Secondarily, if we right-click Install/Update, just install the updates immediately. Currently it does nothing until you click Apply Updates, which just feels wrong to me.

**Comment by OneMoreGres** [comment]
Install/remove the updates immediately sounds good. But it should require the user's explicit action (at least for removal), so no checkboxes.

**Comment by OneMoreGres** [comment]
Removed `apply updates` button in v3.2.0
