### ISSUE TITLE
Add Some Kind of Signalling for "Processing..."

### ISSUE THREAD

**Issue by dsnvwlmnt** [OneMoreGres/ScreenTranslator#48]
The program in general doesn't communicate enough. When you Left-click select something, put a little "Processing..." somewhere, or change the cursor, or anything at all, so you know something is happening. Perhaps the best solution would simply be to keep the red rectangle visible. Sometimes you can't tell if the program isn't working (i.e. will never respond) or if it's processing (i.e. your translation is coming).

Similar issue when Updating. You click Install/Update, but nothing immediately happens, there's no reinforcement. Once you figure out you have to click Apply updates, there's no reinforcement telling you that anything is happening. It takes 5-10 seconds for green progress bars to start appearing (on a modern computer and fast internet connection), but the user may have left the window at this point.

**Comment by OneMoreGres** [comment]
The app's tray icon changes its color depending on state (idle - blue, processing - orange, finished - green, misconfigured - red).
If something does wrong - the app reports errors via tray messages.
The download progress may not be shown at all if the hoster doesn't report the downloaded file's size (as github does). I'll see if I can do something about it.

**Comment by OneMoreGres** [comment]
The app will now show 1% progress just after beginning of the download. Even if no progress can be determined.
