### ISSUE TITLE
There is no thing in update tab.

### ISSUE THREAD

**Issue by lolbraid** [OneMoreGres/ScreenTranslator#49]
version: 3.1.2 I tried also 3.1.0

when I open the app and go to setting and click on update to install translate I can't see any option

**Comment by OneMoreGres** [comment]
Try clicking on the `check now` button. If you have any update errors - install `vcredist-*.exe` files from app folder.

**Comment by lolbraid** [comment]
I tried but doesn't  work

**Comment by lolbraid** [comment]
Thanks it worked
