### ISSUE TITLE
Would be Useful to Enable Copying Original Text to Clipboard (After it's OCR'd)

### ISSUE THREAD

**Issue by dsnvwlmnt** [OneMoreGres/ScreenTranslator#50]
Currently the translation pops up, but there's no way to interact with the popup. It's all or nothing, either the transaltion is good and comprehensible, or not. I often find myself wanting to copy the original text to the clipboard once it's been converted from image to text.

One option would be to make the popup more interactable, so we can text-select and copy to clipboard.

An alternative would be a simple option you turn on or off in the settings. If it's on, whenever the popup is processing/appears, the original text is copied to the clipboard (after it's been OCR'd).

**Comment by OneMoreGres** [comment]
There is a context menu for the popup window. It allows you to do many actions with the result.
You can also copy the result (OCR + translation) to clipboard via tray icon's menu or hotkeys.

**Comment by dsnvwlmnt** [comment]
Oh wow! Thank you.
