### ISSUE TITLE
Screen translator won't work, failed to init OCR engine: init failed

### ISSUE THREAD

**Issue by maportia** [OneMoreGres/ScreenTranslator#51]
**Describe the bug**
I installed the program, installed all all the updates required (recognition, translators, etc.) and tried to translate something but the error "Failed to init OCR engine: init failed" appeared and no matter what I do it still is the same. I went to show translators and in all of them the url is about: blank

**To Reproduce**
1. Go to 'ctrl+alt+z'
2. Click on 'the text I wanted to translate and drag to take a capture'
3. See error 'Failed to init OCR engine: init failed'

**Expected behavior**
wll I expected a window to pop out and show the translation instead of the error message

**Logs**
It won't let me take a capture during recording the logs, so I can't send them 

**Screenshots**
![image](https://user-images.githubusercontent.com/82838109/115286078-e5613f80-a10b-11eb-8e5a-e5546b9466c3.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Desktop environment (linux only): [e.g. KDE, Gnome]
 - App version (release archive name): 3.2.0-win32

**Additional context**

**Comment by OneMoreGres** [comment]
My mistake. Updating release

**Comment by maportia** [comment]
I still can't translate anything :(

**Comment by maportia** [comment]
I still can't translate anyrhing, the same error happens

**Comment by OneMoreGres** [comment]
Reinstall the recognition language

**Comment by maportia** [comment]
it works, thank you!
