### ISSUE TITLE
Failed to init ocr engine

### ISSUE THREAD

**Issue by bmohammed0227** [OneMoreGres/ScreenTranslator#54]
Hi,
I have this error when i try to capture and translate a sentence : 
![Capture](https://user-images.githubusercontent.com/59083322/120890795-374f1d80-c605-11eb-93de-dc953dee513e.PNG)
I have vcredist 2010 and i tried both libraries versions (Compatible and Optimized).

**Comment by OneMoreGres** [comment]
Don't ignore the issue template, please. It's there for a reason. I don't know what version/language you're using and log file could help too.
Try reinstalling the language via updates or switch to portable mode. Also try moving the app to path that contains english-only characters

**Comment by bmohammed0227** [comment]
It works after the reinstallation, thanks.
Time to learn some languages :) Have a good day !
