### ISSUE TITLE
About an recognition bug

### ISSUE THREAD

**Issue by AspirinEny** [OneMoreGres/ScreenTranslator#55]
**Describe the bug**
The capital letter 'I' is always recognized as a separator '|'

**Comment by AspirinEny** [comment]
Comment: The recognition language is English.

**Comment by AspirinEny** [comment]
![image](https://user-images.githubusercontent.com/20171531/122115860-79732d00-ce57-11eb-91c7-81248bfd085c.png)

**Comment by OneMoreGres** [comment]
Change the font of the source text or add a user substitution `|` to `I` in the app settings.
You can also [train your own tesseract model](https://tesseract-ocr.github.io/tessdoc/tess4/TrainingTesseract-4.00.html) based on your data :)
