### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by Wire-Whale** [OneMoreGres/ScreenTranslator#57]
hi, unfortunately after capturing a paragraph; OCR will break lines of that paragraph and then will upload them to translator engine in this problematic shape! for example you can see this on my screenshot:
![screen-translator-problem](https://user-images.githubusercontent.com/86320914/122986485-91dfcc00-d3b0-11eb-8111-391d5c929605.jpg)
one of the consequences is that translated sentence will break apart too; for example in some languages verbs come at end of the sentences unlike English that comes first so if translator can't detect end of the paragraph, it will put verbs in middle of translated sentence or somewhere else that it shouldn't be.
now to solve this issue, I suggest to apply a 'break line removal' code on output of OCR before program upload captured paragraph to the translators or even to be displayed on screen.
I appreciate if you could solve this problem, thanks!

**Comment by OneMoreGres** [comment]
You can enable user substitutions and add a substitution from end-of-line character '\n' to space ' ' in settings.

**Comment by Wire-Whale** [comment]
oh sorry, I didn't notice this capability in first glance
thank you for answer
