### ISSUE TITLE
No source languaje set

### ISSUE THREAD

**Issue by cllach** [OneMoreGres/ScreenTranslator#58]
Sorry, cause maybe it's too obvious and I can see it, but when capturing screen zone it gives me back the message:
No source languaje set.
In Settings, in the Recognition tab (in red), there is no option avalaible  in the Default languaje combo box.

In Settings, in the Translation tab (in red), it appears as translation path: _C:/Users/cllach/AppData/Roaming/Gres/ScreenTranslator/assets/translators_
but this path doesn't exists in my pc, 
and in the same Translation tab, I've choosen English in the Languaje combo box.
and in the same Translation tab too, in the text box below, labeled Translators, there is not any contents.

And in the Update tab (also in red), it seems that I can load correction, recognizers and translators (I have loaded Bing and Google, and some languajes in recognizers and translators), but it seems not change anything.

After setting all as told, first time I press ctrl+alt+Z, or it gives me back again same message,  No source languaje set, or nothing happens and the program seems to close itself at all: disappear the icon from the system tray and the process from the task manager, or does some other weirdy things as leave non sense text in the clipboard.

I'll thank you any help about it.

**Comment by OneMoreGres** [comment]
Hi!
Go to `Updates` page, install (via context menu) wanted `recognizers` and some (or all) `translators`. Then set wanted language in `Recognition` page and enable/reorder some translators in `Translation` page.
Should work then

**Comment by cllach** [comment]
Hello and thanks for your quick answer.
I think I´ve been trying as you indicate, but not being able to make it work..
I'm attaching a pptx with screen captures, maybe you can tell me what I'm doing wrong,
Thanks again and best wishes.


[Screen Translator Picks.pptx](https://github.com/OneMoreGres/ScreenTranslator/files/6771604/Screen.Translator.Picks.pptx)

**Comment by OneMoreGres** [comment]
Try `compatible` library version on `recognition` page

**Comment by cllach** [comment]
Thanks again for your answer, and yes, this time doing like you said, choosing Compatible in Library version, it´s working fine.
Has any downside against the Optimized option ?
Best wishes.

**Comment by OneMoreGres** [comment]
Functionality is the same. It just works a little slower.

**Comment by cllach** [comment]
Ok.
Thanks a lot for your help.
