### ISSUE TITLE
Help Yandex translation

### ISSUE THREAD

**Issue by olenteeth** [OneMoreGres/ScreenTranslator#60]
how to do capcha yandex in english, i don't known russian and show the image
![huhu](https://user-images.githubusercontent.com/87477758/125781142-0d183df3-9daa-4a8a-af7f-c4cec82a7bdd.PNG)

**Comment by olenteeth** [comment]
> At first click on the icon with picture right to the url address. It toggles image loading. Maybe then the captcha will make sense.
thanks, how about russian language, i failed 5 times

**Comment by OneMoreGres** [comment]
Maybe yandex doesn't localize the captcha.
Also you can try to copy `yandex.js` to, say, `yandex_com.js` and replace `..yandex.ru` to `yandex.com` in it. Then enable `yandex_com` translator in the settings on the `Translation` page. You can find the path to the scripts on the same page.

**Comment by olenteeth** [comment]
> Maybe yandex doesn't localize the captcha.
> Also you can try to copy `yandex.js` to, say, `yandex_com.js` and replace `..yandex.ru` to `yandex.com` in it. Then enable `yandex_com` translator in the settings on the `Translation` page. You can find the path to the scripts on the same page.

oh, thanks, all problem solved, i will close this issues
