### ISSUE TITLE
Add Support for Multiple Screens

### ISSUE THREAD

**Issue by dsnvwlmnt** [OneMoreGres/ScreenTranslator#62]
Problem: Currently if you have multiple monitors and hit the translate keybind, it only recognizes your Main monitor. If you move the cursor off to another monitor, the cursor changes from crosshair to normal pointer as though ScreenTranslator doesn't exist.

Solution: Don't limit the screen grabbing cursor detection to the main monitor coordinates. I'm not super familiar with how, but you may only need to slightly change your code, for e.g. to allow negative coordinates instead of assuming 0,0 is the top left corner.

There are no bugs or anything, ScreenTranslator gracefully continues to work on the main screen. Though you get some funny-seeming behavior: while you have ScreenTranslator on (ctrl+alt+z), if you drag a window from another monitor onto the Main monitor, the window will seem to disappear. It reappears when you're done translating.

**Comment by OneMoreGres** [comment]
Actually it should work for multiple screens. When you start capturing, it loops through all the available screens and creates a top-level placeholder window on each one with its screenshot (that describes a funny behavior). 
What app's version and OS do you use?

**Comment by dsnvwlmnt** [comment]
I was using 3.1.2, though I just updated to 3.2.1 and the issue remains.

Windows 10 LTSC 2016, 10.0.14393

![image](https://user-images.githubusercontent.com/14173022/134521794-422d0b87-f56a-4fe2-8b78-afbaec3e6a3f.png)

**Comment by OneMoreGres** [comment]
It doesn't work for any placement of the 2nd screen (left/right/below 1st)? Or just if the 2nd screen is above the 1st?

**Comment by dsnvwlmnt** [comment]
![image](https://user-images.githubusercontent.com/14173022/134658702-d6b067a2-325a-4009-a9f4-bfda929e6336.png)

(The screenshot is more comprehensible, but I typed up most of the below first.)

OK tracing my steps in case anything weird happens:
1) ScreenTranslator is closed
2) Change monitor setup from above, to (2) left of (1), top left corner alignment
3) Launch ST, same story, popup and crosshair on (1), but do not appear on (2)
4) Change monitor setup putting (2) below, aligned left (ST kept open)
5) **Popups and crosshair appear on both monitors!**
6) Change monitor setup putting (2) to the right, aligned top (ST kept open)
7) **Popups and crosshair appear on both monitors!**
8) Change monitor setup putting (2) above (1), aligned right, like original screenshot above (ST kept open)
9) Popup and crosshair on (1), but **do not appear** on (2)
10) Change monitor setup to (2) left of (1), top left corner alignment (ST kept open)
11) Do not appear (somewhat expected, as in step 2)
12) Change monitor setup putting (2) below, aligned left (ST kept open)
13) Popups and crosshair appear on both monitors (as expected)
14) Close ST, change to (2) on the right, top aligned
15) Launch ST, popups and crosshair appear on both monitors (as expected)
16) Then took screenshots of above scenarios and did further non-adjacency tests, and tried swapping primary monitor
17) The "strange" behavior is that the crosshair appears on both monitors, except the left part of the larger one. I can click+drag the ST selector across both monitors, but if I drag into the left part of the larger one, I enter a seeming deadzone (sample image at the bottom of the examples)

**Comment by OneMoreGres** [comment]
Wow. That's exhaustive :)
I got some ideas. I'll check them when I have the opportunity

**Comment by OneMoreGres** [comment]
It should work fine with 3.2.2
