### ISSUE TITLE
yandex transtlate not work

### ISSUE THREAD

**Issue by aarrpp** [OneMoreGres/ScreenTranslator#63]
Версия 3.2.1
Яндекс переводчик не работает.

**Comment by OneMoreGres** [comment]
Он работает. Просто для работы он требует видимое (или даже активное) окно переводчика (правый клик по трею -> "Показать переводчик"). Еще один переводчик (не помню какой именно) требует тоже самое.

**Comment by aarrpp** [comment]
Спасибо, помогло.  В окне яндекс требовал капчу.
