### ISSUE TITLE
Захват сохраненных зон

### ISSUE THREAD

**Issue by aarrpp** [OneMoreGres/ScreenTranslator#64]
В чем смысл функций "Захват сохраненных зон" и "Повторить захват"?
Я не увидел отличия от функции "Захват".

Хотелось бы чтобы программа запоминала ранее отмеченную для захвата область и при вызове "повторить захват" вновь ее обрабатывала.  Сейчас так не происходит.

**Comment by OneMoreGres** [comment]
"Захват сохраненных зон"  - распознает сохраненные (через контекстное меню, там галочка) зоны на новом скриншоте. Как раз то, что вы предлагаете.
"Повторить захват" - распознает новую зону (нужно выделить) на последнем распознаваемом скриншоте.

**Comment by aarrpp** [comment]
По поводу захвата сохраненных зон - к сожалению не понял про какое контекстное меню идет речь.
По поводу "Повторить захват" - все же в чем отличие от обычного захвата?

**Comment by OneMoreGres** [comment]
Контекстное меню в режиме захвата (Ctrl+Alt+Z по умолчанию). Для вызова надо либо кликнуть правой кнопкой при выделении зоны, либо сразу выделять правой (есть подсказка в одном из углов).

Обычный захват делает скриншот и дает пользователю выделить область для распознавания. "Повторить захват" не делает новый скриншот, а использует предыдущий. Попробуйте перейти в режим захвата, выйти из него, передвинуть какое-нибудь окно и нажать на "Повторить захват". Окно будет на старом месте.

**Comment by aarrpp** [comment]
> Контекстное меню в режиме захвата (Ctrl+Alt+Z по умолчанию). Для вызова надо либо кликнуть правой кнопкой при выделении зоны, либо сразу выделять правой (есть подсказка в одном из углов).

Нашел нужное контекстное меню только при выделении правой кнопкой мыши. Спасибо.
Если просто кликнуть правой кнопкой мыши на зоне, то там нет галки.
Мне кажется нужна более подробная документация по описанию этих моментов.

> 
> Обычный захват делает скриншот и дает пользователю выделить область для распознавания. "Повторить захват" не делает новый скриншот, а использует предыдущий. Попробуйте перейти в режим захвата, выйти из него, передвинуть какое-нибудь окно и нажать на "Повторить захват". Окно будет на старом месте.

Ясно, спасибо.

**Comment by OneMoreGres** [comment]
Что-то есть [здесь](https://translator.gres.biz/page/usage/). Что-то в окошке в режиме захвата. Все равно документацию почти никто не читает :) Даже если встроить ее в программу..
