### ISSUE TITLE
Не работает.При попытке перевести выдает Ошибка инициализации OCR. Doesn't work. When trying to translate, it gives  OCR initialization error

### ISSUE THREAD

**Issue by geft878ftt** [OneMoreGres/ScreenTranslator#68]
![КПКЦ](https://user-images.githubusercontent.com/84080923/136018155-96cc25d8-e75a-4137-9be9-e22df6b0e5d9.PNG)

**Comment by OneMoreGres** [comment]
Просьба не игнорировать шаблоны issue. Без дополнительной информации, которую они предлагают ввести гораздо сложнее определить, в чем проблема.
Есть несколько похожих issues, возможно в какой-то из них есть решение (https://github.com/OneMoreGres/ScreenTranslator/issues?q=is%3Aissue+is%3Aclosed+OCR+init)

**Comment by OneMoreGres** [comment]
Какая версия программы\ОС? Какой язык установлен для распознавания? Portable режим или нет? Проблема всегда была или недавно появилась? Если поменять язык распознавания проблема остается? Устанавливали через вкладку обновлений или вручную?
Попробуйте переустановить язык. Возможно при скачивании что-то побилось.

**Comment by orocnogu** [comment]
OC: win 10
APP: 3.2.1
Режимы пробовал все
Я только сегодня попробовал программу
Обновления ставил через настройку
Пробовал переводить en -> ru и ru-> de
Несколько раз пробовал переустанавливать все обновления (языки, автокоррекцияю и api переводчиков)

**Comment by OneMoreGres** [comment]
Попробовал на win10 - отработало без ошибок. 
Попробуйте включить в настройках запись в лог-файл и обновить настройки, чтобы возникла ошибка (например сменить язык и нажать ок). Потом скииньте этот файл сюда или на почту. Возможно на какую-нибудь мысль наведет...

**Comment by OneMoreGres** [comment]
Закрываю из-за неактивности
