### ISSUE TITLE
How come the japanese transaltions are so bad

### ISSUE THREAD

**Issue by CommicKick69ing** [OneMoreGres/ScreenTranslator#7]
秀尽学圏の皆さル、 おはようごさいます。
聞もなく泪掃活動を關始します。

Screen translator: I ’m so happy with you. We will start crushed life without orchids.

google translation: Good morning to all the students in the school.
The cleanup activities will begin without any questions.

How come the translations are so inacurate? (There are more examples I have than just this)

**Comment by OneMoreGres** [comment]
There are at least 2 reasons:
1. Incorrect recognition. If the recognized text doesn't match the original then you'll never get the correct translation. If you see that the recognized text is incorrect, try to select and recognize it again.
2. Different translation services. Then can give different translations for the same input data. You may try to choose the ones that give the best results.
Both of these steps are provided by a side library/service, so there are almost no ways to tune it.
Related to #5
