### ISSUE TITLE
OCR fails to INIT on RECOGNITION = Japanese

### ISSUE THREAD

**Issue by tgbwo** [OneMoreGres/ScreenTranslator#71]
**Describe the bug**

As the title says.

**To Reproduce**

Process as outlined in your docs,  after all updating done.

Set recognition to Russian.
Capture Russian text (not image).
Works fine.

Set recognition to Japanese.
Capture Japanese (Kanji)image text.
"OCR failed to INIT."
Capture Japanese text (Kanji) text.
"OCR failed to INIT."
Capture Romanized Japanese text text.
"OCR failed to INIT."
Set recognition to any European language.
Capture any Japanese.
No OCR error, but as expected translation is gibberish.

**Expected behavior**

Translation as advertised.

**Logs**

[screen-translator-2021-11-25-11-03-42.txt](https://github.com/OneMoreGres/ScreenTranslator/files/7604224/screen-translator-2021-11-25-11-03-42.txt)

Log process:

Capture Kanji image, get error.
Capture Kanji text, get error.
Capture Romanized Japanese text, get error.

**Screenshots**

Unnecessary.

**Desktop (please complete the following information):**

Win7 Home Premium, Service Pack 1, 64 bit - Admin
ScreenTranslator-3.2.0-win64

**Additional context**

Acquired program specifically for Kanji images. According to other users here, it should work. Doesn't.

Suggestion:

A 'readme.txt' in download would have saved much hairpullng.
It is never made clear the DL is incomplete, and useless until additional update steps are taken.
The cryptic 'Setup Error' is insufficient to explain "Why doesn't it work!!!"

**Comment by OneMoreGres** [comment]
Try 3.2.1 version and reinstall all resources installed from the app. 3.2.0 could corrupt some downloads. It's most likely that it fails to init the OCR language because of it.

There is a help section in the app settings window. I can add something there to spare some hair. Just point the most confusing/unclear parts.
There is a generic error message in the tray and more detailed error messages per section in the settings window to understand what's wrong.
And what's a `Setup Error`? Didn't find it in the sources.

**Comment by tgbwo** [comment]
Changing to v3.2.1 resolved problem. Thnx.

"Setup Error". Sorry, my shorthand. Without going back to re-perform clean install, I think actual tray msg. was "Error in Setup".

I have written a short .txt file outlining my belief clearer setup instructions:

[SETUP.txt](https://github.com/OneMoreGres/ScreenTranslator/files/7606785/SETUP.txt)

Edit as you see fit.

Thanks again.

**Comment by OneMoreGres** [comment]
Thanks for the setup instructions. I'll use it for the next version.
