### ISSUE TITLE
Not working at all on linux

### ISSUE THREAD

**Issue by KrischnaGabriel** [OneMoreGres/ScreenTranslator#73]
**Describe the bug**
The App doesn't work on linux at all.

**To Reproduce**
1. Install Linux Mint (should behave the same on Ubuntu or Debian as they're all very similar under the hood)
2. Download the ScreenTranslator AppImage from the releases GitHub page
3. execute: chmod +x ScreenTranslator*
4. start ScreenTranslator

**Expected behavior**
Something useful like a GUI window or an message how to resolve the occurred issue(s)
aka a working application

**Logs**

`user@FUJITSU:~$ ./ScreenTranslator-3.2.1.AppImage `
`"No translators loaded from\n/home/user/.local/share/Gres/ScreenTranslator/assets/translators\n(google.js)"`
`"Incorrect settings found. Go to Settings"`
`^C`
`user@FUJITSU:~$ ls /home/user/.local/share/Gres/ScreenTranslator/assets/`
`ls: cannot access '/home/user/.local/share/Gres/ScreenTranslator/assets/': No such file or directory`

Yes, the regex and quotes were printed out, just like that.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2 
 - Desktop environment (linux only): Cinnamon
 - App version (release archive name): 3.2.1

**Additional context**
After reading the GitHub Usage section, the --help and --help-all options, i still have zero clue, how the app is supposed to be interacted with.
Is it command line only, where are the updates page and settings window, where are the Settings, what do I have to do with the google.js file and why isn't there any information or description about all that stuff?
Get the point?

**Comment by OneMoreGres** [comment]
Hi. The app doesn't have a main window. It starts to the tray icon. You can interact with it via that icon.
On the first run go to settings->updates and install some recognizers and translators. Then enable translators in the corresponding tab of the settings.

**Comment by OneMoreGres** [comment]
Guess it helped
