### ISSUE TITLE
Текст выходит за экран

### ISSUE THREAD

**Issue by Shura-Joy** [OneMoreGres/ScreenTranslator#74]
При попытке перевести текст находящийся близко к краю экрана окно результата выходит за пределы экрана.
<img width="960" alt="EN7NHk0TTW" src="https://user-images.githubusercontent.com/40319205/146570835-acf6fc81-8ca4-44e0-b1a0-598b3dd47676.png">

**Comment by OneMoreGres** [comment]
Привет. Я добавлю дополнительные проверки.
Пока можно размер шрифта уменьшить, чтобы текст влезал.

**Comment by OneMoreGres** [comment]
Добавил проверки в 3.2.3
