### ISSUE TITLE
Доступ запрещён. Отсутствуют ассеты. Базовый функционал не работает без интернета.

### ISSUE THREAD

**Issue by Wrascon** [OneMoreGres/ScreenTranslator#75]
Со старта программы посыпались ошибки.
Не удалось запустить переводчик, путь к файлам TESSDATA не найден (зачем было указывать свой путь и не давать выбрать нам свой?)
![image](https://user-images.githubusercontent.com/17739216/146627909-453166cc-42c1-4377-8bc1-ffaa71ba78b9.png)
Спустя какое-то время опять оповещение "Доступ запрещён", говорит updates.json.
![image](https://user-images.githubusercontent.com/17739216/146627857-ba747d40-88a1-4917-8034-80b3845c9982.png)

Теперь смотрю саму программу. В appdata фигурирует ваша учётка, а подобных файлов в архиве я не нашёл, да и указать нельзя ни один Язык по умолчанию, список пуст.
![image](https://user-images.githubusercontent.com/17739216/146627931-2e7f9e08-9f4b-41a4-adc2-ed79283aa7f3.png)
Перевод также пуст, выбора нет.
![image](https://user-images.githubusercontent.com/17739216/146628013-56c3b7d1-5565-40e7-add6-78a990704ed1.png)
Окно обновлений повторяет "Доступ запрещён" от updates.json.
![image](https://user-images.githubusercontent.com/17739216/146628044-b13f2b7b-80c8-44e1-be54-8311a21319ae.png)
В конечном итоге осознал, что данная программа попросту не работает в оффлайн режиме и всё это время долбилась выйти в интернет
![image](https://user-images.githubusercontent.com/17739216/146628103-5e1a10d5-5a64-499d-afcc-84b758882e58.png)

P.S. Зачем давать возможность выбирать всё из списка, но само удаление проводить по одной строке, после которого раскрывающийся список будет каждый раз сворачиваться?
![image](https://user-images.githubusercontent.com/17739216/146628194-9e8e5f08-67ab-4aa8-88d9-6bf1f9b88747.png)

**Comment by Wrascon** [comment]
Дал ей интернет, выделил область для перевода, не выходит на связь. Запускал от админа
![image](https://user-images.githubusercontent.com/17739216/146628799-ac37a2a9-bed0-4488-8d16-c829b4456b16.png)
![image](https://user-images.githubusercontent.com/17739216/146628794-03bcc977-90fa-4453-a0cb-eb6b856f919b.png)

**Comment by OneMoreGres** [comment]
После первого запуска надо установить некоторые ресурсы для работы (языки, словари). Для этого нужен доступ в интернет. Также он нужен для перевода текста (т.к. перевод осуществляется через яндекс, гугл, ...). Если нужно только распознавать текст, то интернет не нужен.

По поводу удаления не совсем понял. Только что выделил несколько строк, выбрал в меню "удалить" и все они удалились.

От админа запускать не нужно.

По поводу "не выходит на связь". На верхнем скрине пишет, что интернета ей все-таки не досталось. Может еще какие-то ошибки есть? (в нижней части окна или в логе, если его в настройках включить). Или дело не только в файрволе (прокси?)

**Comment by welcomesun** [comment]
Проблему от автора Темы подтверждаю, тестировалось при запуске на 2-х ПК без всяких ограничений выхода в интернет, переводчик не может получить данные по адресу указанному на скриншоте с сайта Github. Порядок ошибок такой: 

при запуске Транслитера, ещё до входа в настройки появляются первые две ошибки, после входа в настройки на вкладку обновления выскакивает ошибка №-3 о невозможности скачать файл апдейта с гитхаб. [2021-12-23_013705](https://user-images.githubusercontent.com/14134409/147163423-5410ce2c-a290-44c7-affa-6510b96908f9.jpg)

Гипотезы с фаерволом вообще не при делах. 
Программа стала практически незаменимой, очень помогает в работе. 
Разберитесь пожалуйста с проблемой. Удачи.

**Comment by OneMoreGres** [comment]
Какие ошибки выводятся в логе? (Лог включается в настройках). vsredist оба установлены?

**Comment by welcomesun** [comment]
Нет, эти компоненты установлены небыли. устанавливая переводчик на новую систему я уже не помнил что требуется до-установить эти пакеты, а так же как именно установить язык для опознавания + сами переводчики. а это совсем не очевидный момент. вопреки привычной логике работы с windows приложениями, что бы установить требуемый язык или переводчик требуется (Важно!) - двойной клик по строке с нужным компонентом, после чего вдруг начинается заветная загрузка. Но к этому приходишь не сразу, а уже после десятка попыток выделить компонент + нажать предлагаемые в интерфейсе кнопки - "Применить" или "Ок", получая многократную ошибку, постоянно предлагающую вернуться в настройки, в которых мы уже и так находимся. всё это повергает в лютую непонятку происходящего, бесполезные перезапуски программы, перезагрузки пк и т.п.  не помешал бы хотя бы редми а лучше видео инструкция на минуту времени. сейчас всё работает. спасибо.

**Comment by OneMoreGres** [comment]
Обновлениями можно управлять через контекстное меню (правый клик). Двойной клик - для установки без меню.
Небольшая инструкция есть [здесь](
https://translator.gres.biz/page/download/#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0) В настройках->помощь тоже есть небольшая подсказка. Если в них что-то не ясно - пишите, что конкретно. По возможности подправлю.
По поводу предложения вернуться в настройки - как-нибудь переформулирую.

**Comment by welcomesun** [comment]
Спасибо за информацию, в инструкции всё очень наглядно. к сожалению не видел её когда очень хотелось.) Вообще проект ваш уникальный, для Windows я не нашёл альтернатив десктопных в принципе, не говоря уже о том что программа в свободном доступе. Отлично переводит внутри запущенных приложений, игр и тп.  Большая благодарность вам за это!🙏

пользуясь случаем хотел сказать про один типо баг, это проблема с опознаванием заглавной латинской "I" переводчик воспринимает её как вертикальную черту, прям строго. Возможно это не со всеми шрифтами. но хорошо было иметь возможность как-то переучивать "опознаватель", например сохранить профиль с корректировкой, где найденная | всегда = I или что-то подобное.

**Comment by OneMoreGres** [comment]
Альтернативы есть,. Сразу на ум только QTranslate приходит, но наверняка еще есть.
По поводу "I" - есть такое дело (#76).

**Comment by welcomesun** [comment]
> По поводу "I" - есть такое дело (#76).
это полностью решает проблему! не видел этой темы. спасибо!

**Comment by Wrascon** [comment]
Бесполезно без прокси. Перевод показывает на одну секунду, в сером окне из текста выводится лишь первое слово.
![image](https://user-images.githubusercontent.com/17739216/147416566-f09983da-a228-460b-b569-fb8520cae28f.png)
Всё остальное выводит прочитать только через отдельное окно с переводом, пока оно не уйдёт в проверку роботом. Капчу же в это окне пройти невозможно без нажатия показать картинки.
![image](https://user-images.githubusercontent.com/17739216/147416495-2b1b0bb7-82c2-400a-871a-fe3b223af8b4.png)

**Comment by OneMoreGres** [comment]
По поводу отображения только первого слова перевода - косяк, посмотрю.

Скрытие картинок по умолчанию сокращает время загрузки страницы и экономит трафик. Не сильно, но все же.

Капча часто выскикивает отчасти из-за большого числа зон распознавания. Т.к. каждая зона распознается и переводится отдельно.

Штатного автоопределения языка в библиотеке нет.

Версии библиотеки отличаются только скоростью работы. Скриптов потому и много, чтобы можно было подходящие\рабочие выбрать и чередовать их (автоматически, если включено несколько переводчиков), чтобы капчи дольше не было.

Насчет сохранения зон подумаю.

Можно отключить отображение исходной картинки и распознанного текста, если они не нужны.

Распознавание выполняется при помощи библиотеки tesseract. В свое время пробовал различные обработки изображения. Но в среднем лучше всего распознавалась исходная картинка.

**Comment by OneMoreGres** [comment]
Закрываю из-за неактивности
