### ISSUE TITLE
Некорректный перевод буквы I

### ISSUE THREAD

**Issue by Artlemoon** [OneMoreGres/ScreenTranslator#76]
Когда в тексте присутствует большая буква I то почему-то ее переводят как палку, как это можно пофиксить?
![text](https://user-images.githubusercontent.com/95495491/146639469-e43519df-666e-4b09-ac69-b218b8a4a8c5.png)

**Comment by V1H4** [comment]
Добавь этот символ в коррекцию.
 ![Снимок1](https://user-images.githubusercontent.com/25763198/146694629-7e4bd350-20ac-4bfd-9987-4ac1f6c0ee56.PNG)

**Comment by Artlemoon** [comment]
> Добавь этот символ в коррекцию. ![Снимок1](https://user-images.githubusercontent.com/25763198/146694629-7e4bd350-20ac-4bfd-9987-4ac1f6c0ee56.PNG)

О, реально помогло. Спасибо тебе добрый человек

**Comment by OneMoreGres** [comment]
Да, добавление символа в пользовательскую коррекцию пока единственный рабочий вариант.
