### ISSUE TITLE
Recognition Language Not Set, no option to set it

### ISSUE THREAD

**Issue by Redduxx99** [OneMoreGres/ScreenTranslator#77]
There is nothing in the tessdata path it wants me to add tessdata to and there were no instructions on what to do (windows) except run the exe. What now?

**Comment by edgartaor** [comment]
I have the same problem. Any ideas?

**Comment by OneMoreGres** [comment]
Open the settings window (via the tray icon). Then go to the updates page and install the desired recognition languages and all translators. Then select the default recognition and translation languages and enable some (or all) translation scripts. Apply settings.
