### ISSUE TITLE
Ошибки в распознавании очень коротких строк

### ISSUE THREAD

**Issue by kirrvin** [OneMoreGres/ScreenTranslator#78]
Если строка короткая, при распознании выдаёт кучу непонятных символов. Особенно видно для последних строк многострочного текста 
Примеры:
[https://disk.yandex.ru/i/op5wRQLueDQkAg](url)
[https://disk.yandex.ru/i/j6D5BqMgkEOZsw](url)

**Comment by OneMoreGres** [comment]
Да, через раз распознает. Если нижняя граница выделения практически по тексту, то лучше.
Посмотрю, можно ли что-то сделать.

**Comment by OneMoreGres** [comment]
Доработал распознавание. Лучше поздно, чем никогда )
