### ISSUE TITLE
 ScreenTranslator-3.2.1-win32.zip90.8 MB  ScreenTranslator-3.2.1-win64.zip106 MB  ScreenTranslator-3.2.1.AppImage107 MB  Source code (zip)  Source code (tar.gz)

### ISSUE THREAD

**Issue by ASertyg45F** [OneMoreGres/ScreenTranslator#82]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**
Application log file recorded during an error.
To start recording a log file, open the settings window,
enable the 'write trace file' option and apply the settings.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10, ubuntu 18.04]
 - Desktop environment (linux only): [e.g. KDE, Gnome]
 - App version (release archive name): [e.g. 3.0.0-win32, 3.0.0-compatible-win64]

**Additional context**

**Comment by ASertyg45F** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by OneMoreGres** [comment]
Any updates follow or I should close this issue?

**Comment by kha2008** [comment]
****
