### ISSUE TITLE
Any Chance we get a Feature that allow to focus the window?

### ISSUE THREAD

**Issue by Godyx** [OneMoreGres/ScreenTranslator#86]
I want to use this for my games to translate... but everytime The program focus and the window of my game not..
so i need to click with my mouse the window again to make some actions...
This is not really controller friendly :D any chance that i can keep my game in focus?
Deskpin and other solutions dont work sadly

**Comment by Godyx** [comment]
ah and sry for my bad english :) hope you understand anyway

**Comment by OneMoreGres** [comment]
You can close the result window with escape key. Focus should get back to the previously focused window.

If it doesn't work for you, I'll see what else I can do.

**Comment by Godyx** [comment]
cant close it with escape.. 
I use the tool to translate the text from the game then the box plop but the game window isnt focus anymore.. only a left klick close the pop up and the game runs again

**Comment by OneMoreGres** [comment]
Ok, I'll try some things, but it won't be soon likely :)
Btw, what OS do you use? I can post some release candidates when they're ready, so you could test them

**Comment by Godyx** [comment]
That would be awesome :)
Thanks so mutch
Windows 10

**Comment by OneMoreGres** [comment]
There is an [intermediate version](https://ufile.io/vjsym19z) (md5 `07ebadde195e2ccced9f117d35316730` ScreenTranslator-3.2.2-win64.zip). It enables the ability to close result widgets via escape key. You can test it and check if it's enough.

**Comment by OneMoreGres** [comment]
Added some fixes in 3.2.3 (close via escape)
