### ISSUE TITLE
Segmentation fault in version 3.2.2

### ISSUE THREAD

**Issue by ParthSindhu** [OneMoreGres/ScreenTranslator#88]
**Describe the bug**
On starting the AppImage for version 3.2.2, there is a segmentation fault and crash on elementary os 6.1

**To Reproduce**
`chmod +x ScreenTranslator-3.2.2.AppImage`
`./ScreenTranslator-3.2.2.AppImage`

**Expected behavior**
The app should start

**Logs**
See screen shot

**Screenshots**
![Screenshot from 2022-03-02 03 25 13](https://user-images.githubusercontent.com/38955822/156323821-d6bfc1ac-69f9-4218-b126-18aec048c980.png)

**Desktop (please complete the following information):**
 - OS: elementary OS 6.1 Jólnir
 - Desktop environment (linux only): Panheon
 - App version (release archive name): 3.2.2

**Additional context**
The app starts as expected with version 3.2.1 but 3.2.2 crashes

**Comment by OneMoreGres** [comment]
I'll check this

**Comment by psqq** [comment]
Same for 3.2.1 and 3.2.2:

```
DevTools listening on ws://127.0.0.1:56097/devtools/browser/9e96b609-5102-4246-a4a9-ddac38f60b94
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:56097
Segmentation fault (memory stack flushed to disk)
[3:3:0100/000000.305087:ERROR:zygote_linux.cc(614)] Zygote could not fork: process_type renderer numfds 3 child_pid -1
[3:3:0100/000000.305269:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
```

**Comment by OneMoreGres** [comment]
Try setting `QTWEBENGINE_DISABLE_SANDBOX=1` (e.g. `QTWEBENGINE_DISABLE_SANDBOX=1 ./ScreenTranslator-3.2.2.AppImage`)

**Comment by OneMoreGres** [comment]
Also using [this](https://github.com/OneMoreGres/ScreenTranslator/issues/86#issuecomment-1092168475) version with or without `QTWEBENGINE_DISABLE_SANDBOX=1` might work.

**Comment by OneMoreGres** [comment]
Added some words about `QTWEBENGINE_DISABLE_SANDBOX=1` to readme
