### ISSUE TITLE
selecting a paragraph resulted in separated lines of text

### ISSUE THREAD

**Issue by vtminhh** [OneMoreGres/ScreenTranslator#89]
when i select a paragraph (in chinese), the program recognizes it as multiple lines of text. i think it should groups all text into 1 line instead.

**Comment by vtminhh** [comment]
![2022-03-16-000094](https://user-images.githubusercontent.com/101307929/158595906-bdb605cf-7800-43fa-8a0c-36bd4c562077.png)
sorry for the late reply. as seen here the text in the chatbox is supposed to be 1 line

**Comment by OneMoreGres** [comment]
There are the same issues (#57, #69)

In short: `You can enable user substitutions and add a substitution from end-of-line character '\n' to space ' ' in settings`

Maybe I'll add a better solution someday. For now I'm closing this issue as duplicate
