### ISSUE TITLE
Only translates to russian

### ISSUE THREAD

**Issue by berkecetin98** [OneMoreGres/ScreenTranslator#9]
Can you help me. Cant translate russian to english
![0a9b0f228030bf8d20c9a9e7b56844d1](https://user-images.githubusercontent.com/51974999/63296320-849ab780-c2d7-11e9-9b05-adc404e75466.png)
![9ab2e344a0e1ecb6c4276b804e752634](https://user-images.githubusercontent.com/51974999/63296324-849ab780-c2d7-11e9-9181-f5c285a56d45.png)

**Comment by berkecetin98** [comment]
ok so sorry. Problem was update obviously. Updated and worked like a charm. Awesome and very helpful program thanks.

**Comment by OneMoreGres** [comment]
Glad it works. Closing issue then.
