### ISSUE TITLE
Текст уезжает

### ISSUE THREAD

**Issue by worldofage** [OneMoreGres/ScreenTranslator#90]
Привет! Очень классное приложение. Но у меня текст уходит далеко вправо, и это видно только при большом шрифте. У меня 2 экрана, может быть проблема в этом.
![image](https://user-images.githubusercontent.com/32104266/158485278-1c85b8e2-13a9-4130-9a57-2e7f88537df6.png)

**Comment by worldofage** [comment]
![image](https://user-images.githubusercontent.com/32104266/158487909-08b34c94-642c-40a6-8215-61cd6adffd2e.png)

**Comment by OneMoreGres** [comment]
Привет! Первый скрин со 2 экрана? Уезжает с обоих? Всегда уезжал или после каких-то настроек начал?

**Comment by worldofage** [comment]
Уезжает с первого. Вообще он скорее просто сдвигается вправо примерно на расстояние моего второго экрана. Я сначала скачал версию с установщиком, там этой ошибки не было. Но в последний версии начались проблемы. Также при пкм на зоне (для настройки) окно тоже уезжает. Тоже примерно на ширину второго экрана
![image](https://user-images.githubusercontent.com/32104266/158530729-c19ac7cb-c2d4-47ef-8596-8a746cf8af84.png)

**Comment by worldofage** [comment]
Все скрины с первого экрана. Уезжает вправо примерно на ширину второго экрана.

**Comment by OneMoreGres** [comment]
Проблема внутри программы, так что настройки не помогут. Буду исправлять. Спасибо за детали
