### ISSUE TITLE
Inappropriate line breaks for latex paper translations 

### ISSUE THREAD

**Issue by mrweims69** [OneMoreGres/ScreenTranslator#92]
Hello, I am a French student, I have been using your application for several weeks in support of understanding scientific articles, it is great thank you very much! 
However, a problem often occurs on the justified texts mainly. 

When I select a text, the automatic line break is considered by the interpreter as a line break.  
This is very detrimental to the translation, which will provide rather random results and a lot of repetition. 

![1](https://user-images.githubusercontent.com/101801418/158793220-0a6c5477-76cd-421e-a0c5-345bcf856b83.jpg)
![2](https://user-images.githubusercontent.com/101801418/158793259-dc26502a-2e6f-4031-912f-8d662bb46240.jpg)

As you can see on the screens, the text is well recognized. Each line break will be interpreted as a new line. 

I think that turning the text into a line is not technically very difficult. And the quality of the translations will be clearly improved. 

Once again, thank you for your work. I'm still available for more details :)

**Comment by OneMoreGres** [comment]
There are the same issues (#57, #69, #89)

In short: `You can enable user substitutions and add a substitution from end-of-line character '\n' to space ' ' in settings`

Maybe I'll add a better solution someday. For now I'm closing this issue as duplicate.

If you have more questions you still can post it here.
