### ISSUE TITLE
Cant open updates to set up

### ISSUE THREAD

**Issue by zishop** [OneMoreGres/ScreenTranslator#93]
Ive tried to figure out how to open this to set it up and can't seem to figure it out, was hoping for more details on how to access the updates and options

**Comment by OneMoreGres** [comment]
Some info is in the [readme file](https://github.com/OneMoreGres/ScreenTranslator#setup). All interaction is done via the tray icon or hotkeys.

**Comment by OneMoreGres** [comment]
Closing the issue. Reopen if you have more questions.
