### ISSUE TITLE
Error URL

### ISSUE THREAD

**Issue by DVOFY** [OneMoreGres/ScreenTranslator#96]
file download error when trying to update

when trying to download the necessary libraries of languages ​​and translators, an error occurred downloading from the link. When manually entering a link, the transition is carried out

 - OS: [e.g. windows 10 x64
- App version 3.2.2
![ngfXoNiEUoE](https://user-images.githubusercontent.com/103877712/163706967-6e6d0f93-72b1-4a7a-b3f0-f275817f965d.jpg)
![MSBatvcbbDI](https://user-images.githubusercontent.com/103877712/163706969-438cb8d9-7a38-4cf4-86a8-c99bffef4aae.jpg)

**Comment by OneMoreGres** [comment]
Did you install both `vcredist` files in the app's folder?
Also enable `write log to file` option in general settings and check for updates to see more details for the error (and post it here).

**Comment by DVOFY** [comment]
I have vcredist installed, I also tried to reinstall it. As a temporary solution, he threw all the files necessary for work in their places

[-](https://github.com/OneMoreGres/ScreenTranslator/issues/96#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/OneMoreGres/ScreenTranslator/issues/96#) <System>
  <Provider Name="Microsoft[-](https://github.com/OneMoreGres/ScreenTranslator/issues/96#)Windows-DistributedCOM" Guid="{1B562E86-B7AA-4131-BADC-B6F3A001407E}" EventSourceName="DCOM" /> 
  <EventID Qualifiers="0">10016</EventID> 
  <Version>0</Version> 
  <Level>3</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2022-04-17T14:14:33.0944465Z" /> 
  <EventRecordID>15338</EventRecordID> 
  <Correlation ActivityID="{affbe60f-385b-4221-bffc-cc78db2e0474}" /> 
  <Execution ProcessID="456" ThreadID="7608" /> 
  <Channel>System</Channel> 
  <Computer>DESKTOP-2DB4JG7</Computer> 
  <Security UserID="S-1-5-21-281633461-2566543538-2268235762-1001" /> 
  </System>
- <EventData>
  <Data Name="param1">по умолчанию для компьютера</Data> 
  <Data Name="param2">Локально</Data> 
  <Data Name="param3">Активация</Data> 
  <Data Name="param4">{C2F03A33-21F5-47FA-B4BB-156362A2F239}</Data> 
  <Data Name="param5">{316CDED5-E4AE-4B15-9113-7055D84DCC97}</Data> 
  <Data Name="param6">DESKTOP-2DB4JG7</Data> 
  <Data Name="param7">danik</Data> 
  <Data Name="param8">S-1-5-21-281633461-2566543538-2268235762-1001</Data> 
  <Data Name="param9">LocalHost (с использованием LRPC)</Data> 
  <Data Name="param10">Microsoft.Windows.ShellExperienceHost_10.0.19041.1320_neutral_neutral_cw5n1h2txyewy</Data> 
  <Data Name="param11">S-1-15-2-155514346-2573954481-755741238-1654018636-1233331829-3075935687-2861478708</Data> 
  </EventData>
  </Event>
![H_R3K-_jgoo](https://user-images.githubusercontent.com/103877712/163718757-03298e12-9bba-4af6-897f-7f88127c4530.jpg)
![7eZxc-sUg3k (1)](https://user-images.githubusercontent.com/103877712/163718760-ec68e2b3-cd25-49d5-8eec-741cc882cb26.jpg)
[screen-translator-2022-04-17-18-20-42.txt](https://github.com/OneMoreGres/ScreenTranslator/files/8501802/screen-translator-2022-04-17-18-20-42.txt)

**Comment by OneMoreGres** [comment]
There's something with openssl library. So far can't reproduce this error to find the solution.
Try installing openssl 1.1.1 library manually.
Or try to move `libssl-1_1-x64.dll` and `libcrypto-1_1-x64.dll` from the app's folder

**Comment by DVOFY** [comment]
After installing the libraries manually, everything seemed to work fine
