### ISSUE TITLE
Screen placement problem

### ISSUE THREAD

**Issue by Catoryu** [OneMoreGres/ScreenTranslator#97]
If you have multiple screens and your main screen is not the left one, the translation window will be placed in the wrong spot.

0. Have multiple screens. (2 screens is good, if the secondary screen is smaller than the main one, it's even better)
1. Make sure that your main screen is not on the left.
2. Use the translator (Windows OS, version 3.2.2) in window mode on your main screen, simple capture is OK.
3. The window will appear out of screen, if your left monitor is small enough and your capture is on the left side of your main screen, you might see the translation window on the right side of your monitor.

The program should take account of multiple monitors, especially, which is the main monitor.
![image](https://user-images.githubusercontent.com/34058720/163733164-ea8ff818-8a36-4ab4-8bd4-670f6e84199e.png)
I have a monitor on the left side of this one which is smaller, this one is the main monitor, I tried translating the text on the left side of the screen and it appeared on the left side, by what I can see, the width of my other monitor + x position on the main monitor should give approximately the same value as where it appears on the main screen.

 - OS: Windows 10
 - Desktop environment (linux only): [e.g. KDE, Gnome]
 - App version (release archive name): ScreenTranslator-3.2.2-win64.zip

**Comment by OneMoreGres** [comment]
I fixed a similar issue some time ago, but have not published it yet. You can try WIP version from [here](https://github.com/OneMoreGres/ScreenTranslator/issues/95#issuecomment-1092162065).

**Comment by OneMoreGres** [comment]
Added some fixes in 3.2.3
